/* Workspace-first client interaction. All operational requests use Gateway APIs. */
(() => {
  window.workspaceFirstEnabled=true;
  const q=id=>document.getElementById(id),tr=(en,ar)=>lang==='ar'?ar:en;
  const admin=()=>['admin','owner'].includes(currentUser?.role);
  const texts=[];
  function text(tag,en,ar,cls){const node=textElement(tag,tr(en,ar),cls);texts.push([node,en,ar]);return node;}
  function btn(id,en,ar,action,cls='button ghost small'){const node=text('button',en,ar,cls);node.id=id;node.type='button';node.onclick=async()=>{try{await action();}catch(error){toast(error.message);}};return node;}
  function title(en,ar){return text('h2',en,ar);}
  const home=document.createElement('main');home.id='workspaceHomePage';home.className='page portal-page';
  home.innerHTML='<div class="workspace-home portal-content"><div class="work-home-heading"></div><div class="home-actions"></div><label class="session-search"><input id="homeSessionSearch" type="search"></label><section><h2 id="homeProjectsTitle"></h2><div id="homeProjects"></div></section><section><h2 id="homeSessionsTitle"></h2><div id="homeSessions"></div></section></div>';
  q('app-main').append(home);
  home.querySelector('.work-home-heading').append(text('span','YOUR WORKSPACE','مساحة عملك','eyebrow'),text('h1','What will you build today?','ماذا ستبني اليوم؟'),text('p','Open a project, continue a conversation, or start something new.','افتح مشروعًا، أكمل محادثة، أو ابدأ فكرة جديدة.','lead'));
  home.querySelector('.home-actions').append(btn('homeNewProject','New project','مشروع جديد',()=>page('onboarding'),'button'),btn('homeConnections','Settings · Connections','الإعدادات · الاتصالات',()=>openConnections()));
  texts.push([q('homeProjectsTitle'),'Projects / workspaces','المشاريع / مساحات العمل'],[q('homeSessionsTitle'),'Recent conversations','المحادثات الأخيرة']);
  q('homeSessionSearch').setAttribute('aria-label','Search sessions');
  const settings=document.createElement('main');settings.id='connectionsPage';settings.className='page portal-page';
  settings.innerHTML='<div class="portal-content connections-content"><div class="connections-heading"></div><div id="connectionsProviders"></div><div id="connectionsGithub"></div><div id="connectionsRuntime"></div></div>';
  q('app-main').append(settings);settings.querySelector('.connections-heading').append(text('h1','Settings · Connections','الإعدادات · الاتصالات'),text('p','Choose a provider and add its API key. After connection, its available models and agents appear in your workspace.','\u0627\u062e\u062a\u0631 \u0645\u0632\u0648\u0651\u062f\u064b\u0627 \u0648\u0623\u0636\u0641 \u0645\u0641\u062a\u0627\u062d API. \u0628\u0639\u062f \u0627\u0644\u0631\u0628\u0637\u060c \u0633\u062a\u0638\u0647\u0631 \u0646\u0645\u0627\u0630\u062c\u0647 \u0648\u0648\u0643\u0644\u0627\u0624\u0647 \u0641\u064a \u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644.','lead'),btn('connectionsReturn','Return to workspace','العودة لمساحة العمل',()=>activeWorkspace?page('workspacePage'):page('workspaceHomePage')));
  protectedPages.add('workspaceHomePage');protectedPages.add('connectionsPage');
  Object.assign(copy.en,{workspaceHome:'Workspace / Home',connectionsSettings:'Settings / Connections'});
  Object.assign(copy.ar,{workspaceHome:'مساحة العمل / الرئيسية',connectionsSettings:'الإعدادات / الاتصالات'});
  Object.assign(copy.en,{subscriptionNoRefund:'Subscription payments are non-refundable.',clientAccountLead:'Personal details and preferences.'});
  Object.assign(copy.ar,{subscriptionNoRefund:'الاشتراكات غير قابلة لاسترداد المبلغ.',clientAccountLead:'البيانات الشخصية والتفضيلات.'});
  function navButton(id,key,icon,action){const node=document.createElement('button');node.id=id;node.dataset.go=action;node.innerHTML='<svg class="nav-icon"><use href="'+icon+'"/></svg><span data-i18n="'+key+'">'+t(key)+'</span>';node.onclick=()=>page(action);return node;}
  q('clientNav').insertBefore(navButton('clientWorkspaceHome','workspaceHome','#icon-opencode','workspaceHomePage'),q('clientNav').querySelector('button'));
  q('clientNav').querySelector('[data-client-view=dashboard]')?.remove();
  q('clientNav').querySelector('[data-client-view=ai]')?.remove();q('clientNav').querySelector('[data-client-view=github]')?.remove();
  q('clientNav').append(navButton('clientConnections','connectionsSettings','#icon-settings','connectionsPage'));
  const oldClientView=window.openClientView;
  window.openClientView=name=>['ai','github'].includes(name)?openConnections(name==='ai'?'providers':'github'):oldClientView(name);
  q('clientNav').querySelectorAll('[data-client-view]').forEach(button=>button.onclick=()=>window.openClientView(button.dataset.clientView));
  q('adminNav').querySelectorAll('[data-admin-view]').forEach(button=>button.onclick=()=>window.openAdminView(button.dataset.adminView));
  async function loadHome(){
    const data=await api('/api/dashboard');const projects=q('homeProjects');projects.replaceChildren();
    for(const project of data.projects){for(const workspace of project.workspaces){const row=textElement('div','','home-project-row');row.append(textElement('strong',project.name),textElement('small',(project.repository||tr('Local project','مشروع محلي'))+' · '+workspace.status));row.append(btn('home-open-'+workspace.id,'Open workspace','فتح مساحة العمل',()=>openWorkspace(project,workspace)),btn('home-session-'+workspace.id,'New session','جلسة جديدة',async()=>{await openWorkspace(project,workspace);await createSession();}));projects.append(row);}}
    if(!projects.children.length)projects.append(text('p','No projects yet. Create your first workspace.','لا توجد مشاريع بعد. أنشئ مساحة عملك الأولى.','home-empty'));
    const sessions=q('homeSessions');sessions.replaceChildren();
    for(const session of data.recent_sessions){const project=data.projects.find(p=>p.workspaces.some(w=>w.id===session.workspace_id));const workspace=project?.workspaces.find(w=>w.id===session.workspace_id);if(!workspace)continue;const row=btn('home-recent-'+session.id,session.title,session.title,async()=>{await openWorkspace(project,workspace);await selectSession(session);},'home-session-row');row.append(textElement('small',project.name+' · '+session.status));row.dataset.search=(session.title+' '+project.name).toLowerCase();sessions.append(row);}
    if(!sessions.children.length)sessions.append(text('p','No conversations yet. Open a project and start a session.','لا توجد محادثات بعد. افتح مشروعًا وابدأ جلسة.','home-empty'));
    q('homeSessionSearch').placeholder=tr('Search recent sessions…','ابحث في الجلسات الأخيرة…');
    renderEntitlement();q('homeSessionSearch').oninput=()=>sessions.querySelectorAll('[data-search]').forEach(row=>row.hidden=!row.dataset.search.includes(q('homeSessionSearch').value.trim().toLowerCase()));
  }
  async function openConnections(focus){await page('connectionsPage');if(focus)q(focus==='github'?'connectionsGithub':'connectionsProviders').scrollIntoView({block:'start',behavior:'smooth'});}
  window.openConnections=openConnections;
  async function loadConnections(){
    try{await window.renderManagement(q('connectionsProviders'),'providers');}catch(error){q('connectionsProviders').append(textElement('p',error.message,'connection-error'));}
    const github=q('connectionsGithub');github.replaceChildren(title('GitHub account / authorization','حساب GitHub / التفويض'));
    const status=await api('/api/github/status');github.append(textElement('p',status.connected?(status.account_login||'GitHub'):tr('Not connected','غير متصل')));
    const authorize=btn('settingsAuthorizeGithub','Authorize GitHub','تفويض GitHub',()=>window.location.assign('/api/github/install'));authorize.disabled=!status.configured;github.append(authorize);
    if(status.connected)github.append(btn('settingsDisconnectGithub','Disconnect','إلغاء الربط',async()=>{await api('/api/github/disconnect',{method:'POST'});await loadConnections();}));
    github.append(text('p','Repository permissions and installation access are managed in GitHub authorization. Choose your working repository beside the prompt.','تُدار صلاحيات المستودعات والتثبيت عبر تفويض GitHub. اختر مستودع العمل بجوار محرر الطلب.'));
    const runtime=q('connectionsRuntime');runtime.replaceChildren(title('Runtime / Server','وقت التشغيل / الخادم'));const state=await api('/api/opencode/status');runtime.append(textElement('p',state.runtime_mode+' · '+(state.healthy?tr('Healthy','جاهز'):tr('Unavailable','غير متاح'))));
  }
  let workAccess=false,entitlement=null;
  const homeAccess=textElement('div','','access-notice');homeAccess.id='homeAccessState';home.querySelector('.work-home-heading').append(homeAccess);
  const workspaceAccess=textElement('div','','access-notice');workspaceAccess.id='workspaceAccessState';q('promptForm').before(workspaceAccess);
  function renderEntitlement(){if(!entitlement)return;const end=entitlement.access.ends_at,days=end?Math.max(0,Math.ceil((new Date(end)-Date.now())/86400000)):0;homeAccess.replaceChildren(textElement('span',workAccess?(entitlement.access.reason==='trial'?tr('Free trial · ','التجربة المجانية · '):tr('Subscription · ','الاشتراك · '))+days+' '+tr('days remaining','يوم متبقٍ'):tr('Your access has expired. Subscribe to continue.','انتهت مدة الوصول. اشترك للمتابعة.')));workspaceAccess.replaceChildren();workspaceAccess.hidden=workAccess;if(!workAccess){const subscribe=()=>window.openClientView('billing');homeAccess.append(btn('homeSubscribe','Subscribe / Renew','اشترك / جدّد',subscribe));workspaceAccess.append(textElement('span',tr('Read-only workspace. Subscribe to continue coding.','مساحة العمل للقراءة فقط. اشترك لمتابعة البرمجة.')),btn('workspaceSubscribe','Subscribe / Renew','اشترك / جدّد',subscribe));}q('homeNewProject').disabled=!workAccess;q('promptInput').disabled=!workAccess;document.querySelectorAll('#sessionSidebar .new-session,#homeProjects [id^=home-session-],#sessionList .session,#homeSessions [id^=home-recent-]').forEach(n=>n.disabled=!workAccess);if(!workAccess){q('sendMessage').disabled=true;q('commitButton').disabled=true;q('pushButton').disabled=true;}}
  async function refreshEntitlement(){if(!currentUser||admin())return;entitlement=await api('/api/billing/subscription');workAccess=entitlement.access.allowed;if(!workAccess){if(activeSession&&!q('stopAgent').disabled){try{await api('/api/sessions/'+activeSession.id+'/stop',{method:'POST'});}catch(error){toast(error.message);}q('stopAgent').disabled=true;}stopEvents();}renderEntitlement();}
  const previousPage=page;page=async function(id){await authReady;await interfaceReady;if(admin()&&['workspaceHomePage','connectionsPage'].includes(id))id='adminPage';if(currentUser&&!admin()&&['onboarding'].includes(id)){const state=await api('/api/billing/subscription');if(!state.access.allowed){stopEvents();await oldClientView('billing');toast(tr('Your 10-day trial has ended. Subscribe to continue.','انتهت تجربتك لمدة عشرة أيام. اشترك للمتابعة.'));return;}}await previousPage(id);if(!currentUser)return;if(!admin()&&['workspaceHomePage','workspacePage'].includes(id))await refreshEntitlement();if(!admin()&&id==='workspacePage'&&activeWorkspace)await refreshChoices();if(admin()){if(q('adminPage').classList.contains('active')&&document.querySelector('[data-admin-panel=billing].active'))await loadPaymentOrders(true);return;}if(q(id)?.classList.contains('active')){if(id==='workspaceHomePage')await loadHome();if(id==='connectionsPage')await loadConnections();}};
  const shell=document.querySelector('#workspacePage .workspace-shell'),center=shell.querySelector('.agent-column'),pane=q('sessionSidebar'),review=q('reviewPanel');
  shell.classList.add('workspace-first','chat-only');
  q('manageProviders')?.remove();
  const previousShow=showPage;showPage=function(id){if(id==='adminPage'&&!admin()){toast('Administrator access required');id=currentUser?'workspaceHomePage':'authPage';}if(admin()&&['workspaceHomePage','connectionsPage','workspacePage'].includes(id))id='adminPage';pane.classList.remove('open');overlay(false);previousShow(id);q('clientWorkspaceHome').classList.toggle('active',['workspaceHomePage','workspacePage'].includes(id));q('clientConnections').classList.toggle('active',id==='connectionsPage');if(['workspaceHomePage','workspacePage','connectionsPage'].includes(id))q('clientNav').querySelectorAll('[data-client-view]').forEach(n=>n.classList.remove('active'));};
  const projectbar=center.querySelector('.project-bar');projectbar.querySelector('.statuses').hidden=true;
  const context=textElement('div','','composer-context');q('promptForm').prepend(context);context.append(q('workspaceRepo'),q('workspaceBranch'));const gitState=text('span','GitHub: checking…','GitHub: جارٍ التحقق…');gitState.id='workspaceGithubState';context.append(gitState,q('runtimeStatus'));
  const controls=q('promptForm').lastElementChild;controls.classList.add('composer-controls');
  const agent=document.createElement('select');agent.id='agentSelect';agent.hidden=true;agent.setAttribute('aria-label','Agent');agent.title=tr('Agent','الوكيل');controls.insertBefore(agent,q('providerSelect'));
  const connect=btn('composerConnectProvider','Connect provider','ربط مزوّد',()=>openConnections('providers'));controls.insertBefore(connect,q('providerSelect'));
  q('providerSelect').setAttribute('aria-label','Provider');q('modelSelect').setAttribute('aria-label','Model');
  const attach=btn('attachFiles','＋','＋',()=>{},'icon');attach.disabled=true;attach.title=tr('Attachments are not available yet','المرفقات غير متاحة بعد');controls.prepend(attach);
  q('openTools').onclick=()=>window.openConnections('providers');q('openTools').title=tr('Open OpenCode provider and workspace setup','\u0641\u062a\u062d \u0625\u0639\u062f\u0627\u062f \u0645\u0632\u0648\u062f OpenCode \u0648\u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644');q('chatGithub').onclick=()=>openRepositoryPicker();
  const links=center.querySelector('.workspace-links');links?.remove();
  const toolbar=textElement('nav','','workbench-toolbar');toolbar.append(btn('toggleSessions','Sessions / Review','الجلسات / المراجعة',()=>togglePane()),btn('workspaceChat','Conversation','المحادثة',()=>{shell.classList.add('chat-only');shell.classList.remove('review-only');review.classList.remove('open');}));
  for(const [name,en,ar] of [['files','Files','الملفات'],['diff','Changes / Diff','التغييرات / الفروقات'],['logs','Activity','النشاط']])toolbar.append(btn('workspace'+name,en,ar,async()=>{shell.classList.remove('chat-only');shell.classList.add('review-only');review.classList.add('open');await tab(name);}));
  center.insertBefore(toolbar,projectbar.nextSibling);center.append(review);
  const heading=text('h3','Sessions / history','الجلسات / السجل');pane.insertBefore(heading,q('sessionList'));
  const search=document.createElement('input');search.id='workspaceSessionSearch';search.type='search';search.placeholder=tr('Search sessions','ابحث في الجلسات');search.setAttribute('aria-label','Search workspace sessions');pane.insertBefore(search,q('sessionList'));search.oninput=()=>q('sessionList').querySelectorAll('.session').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(search.value.toLowerCase()));
  const workflow=textElement('section','','workspace-activity');workflow.append(title('Workflow / Activity','سير العمل / النشاط'));const events=textElement('div');events.id='workspaceActivity';workflow.append(events);pane.insertBefore(workflow,pane.querySelector('.side-spacer'));
  const reviewActions=textElement('div','','pane-review-actions');for(const name of ['files','diff','logs'])reviewActions.append(btn('pane-'+name,...({files:['Files','الملفات'],diff:['Review / Changes','المراجعة / التغييرات'],logs:['Activity','النشاط']}[name]),()=>q('workspace'+name).click()));pane.insertBefore(reviewActions,workflow);
  const eventObserver=new MutationObserver(records=>{for(const record of records)for(const item of record.addedNodes)if(item.nodeType===1&&item.classList.contains('event-line')){events.append(item.cloneNode(true));while(events.children.length>30)events.firstChild.remove();}});eventObserver.observe(q('agentFeed'),{childList:true});
  function drawer(){return matchMedia('(max-width:1100px)').matches;}
  function closePane(){pane.classList.remove('open');if(!drawer())shell.classList.add('sessions-collapsed');overlay(false);}
  function togglePane(){if(drawer()){pane.classList.toggle('open');overlay(pane.classList.contains('open'));}else shell.classList.toggle('sessions-collapsed');}
  q('openSessions').onclick=togglePane;q('closeSessions').onclick=closePane;q('backdrop').addEventListener('click',()=>{pane.classList.remove('open');});
  q('reviewButton').onclick=()=>q('workspacefiles').click();q('closeReview').onclick=()=>q('workspaceChat').click();
  const oldRefreshGit=refreshGit;refreshGit=async()=>{await oldRefreshGit();q('manageProviders')?.remove();};
  let providers=[],chosenAgent='',chosenProvider='',chosenModel='',discovery=0;
  function updateSend(){q('sendMessage').disabled=!workAccess||!activeSession||!agent.value||!q('providerSelect').value||!q('modelSelect').value||!q('stopAgent').disabled;}
  async function refreshChoices(preferredProvider=''){
    if(!activeWorkspace||admin())return;if(!workAccess){agent.disabled=q('providerSelect').disabled=q('modelSelect').disabled=true;updateSend();return;}const workspaceId=activeWorkspace.id,stamp=++discovery;
    const result=await Promise.allSettled([api('/api/workspaces/'+workspaceId+'/providers'),api('/api/workspaces/'+workspaceId+'/agents')]);if(stamp!==discovery||activeWorkspace?.id!==workspaceId)return;
    providers=result[0].status==='fulfilled'?result[0].value:[];const connected=providers.filter(p=>p.connected),agents=result[1].status==='fulfilled'?result[1].value:[];
    q('providerSelect').replaceChildren(new Option(tr('Provider','المزوّد'),''));for(const p of connected)q('providerSelect').add(new Option(p.name,p.id));q('providerSelect').disabled=!connected.length;
    if(connected.some(p=>p.id===chosenProvider))q('providerSelect').value=chosenProvider;else if(connected.length===1)q('providerSelect').value=connected[0].id;
    agent.replaceChildren(new Option(tr('Agent','الوكيل'),''));for(const a of agents)agent.add(new Option(a.name,a.id));agent.disabled=!agents.length;agent.value=agents.some(a=>a.id===chosenAgent)?chosenAgent:(agents.find(a=>a.id==='build')?.id||agents[0]?.id||'');
    agent.hidden=!connected.length;chosenAgent=agent.value;
    connect.hidden=connected.length>0;
    if(connected.some(p=>p.id===preferredProvider)){chosenProvider=preferredProvider;q('providerSelect').value=preferredProvider;}
    q('providerSelect').onchange=()=>{chosenProvider=q('providerSelect').value;chosenModel='';models();};agent.onchange=()=>{chosenAgent=agent.value;updateSend();};q('modelSelect').onchange=()=>{chosenModel=q('modelSelect').value;updateSend();};models();
    if(!connected.length){q('runtimeStatus').textContent=result[0].status==='rejected'?tr('Runtime unavailable','وقت التشغيل غير متاح'):tr('Connect a provider to begin','اربط مزوّدًا للبدء');}
  }
  function models(){q('modelSelect').replaceChildren(new Option(tr('Model','النموذج'),''));const selected=providers.find(p=>p.id===q('providerSelect').value);for(const model of selected?.models||[])q('modelSelect').add(new Option(model.name,model.id));q('modelSelect').disabled=!selected;q('modelSelect').value=selected?.models.some(m=>m.id===chosenModel)?chosenModel:(selected?.models[0]?.id||'');chosenModel=q('modelSelect').value;updateSend();}
  window.refreshWorkspaceChoices=refreshChoices;
  const originalWorkspace=openWorkspace;openWorkspace=async function(project,workspace){if(admin()){await page('adminPage');return;}chosenAgent=chosenProvider=chosenModel='';shell.classList.add('chat-only');shell.classList.remove('review-only');events.replaceChildren();await originalWorkspace(project,workspace);await refreshChoices();const state=await api('/api/github/status');gitState.textContent=state.connected?'GitHub · '+(state.account_login||tr('Connected','متصل')):tr('GitHub · Not connected','GitHub · غير متصل');q('chatGithub').title=gitState.textContent;renderEntitlement();};
  const originalSession=selectSession;selectSession=async function(session){if(!workAccess){toast(tr('Subscribe to resume this conversation.','اشترك لاستئناف هذه المحادثة.'));return;}await originalSession(session);await refreshChoices();};
  async function createSession(){if(!activeWorkspace)return;await refreshEntitlement();if(!workAccess)return;const b=pane.querySelector('.new-session');b.disabled=true;try{const row=await api('/api/workspaces/'+activeWorkspace.id+'/sessions',{method:'POST',body:JSON.stringify({title:tr('New session','جلسة جديدة')})});await refreshSessions();q('workspaceChat').click();await selectSession(row);}catch(error){toast(error.message);q('runtimeStatus').textContent=tr('OpenCode unavailable','OpenCode غير متاح');}finally{b.disabled=!workAccess;}}
  pane.querySelector('.new-session').onclick=createSession;
  q('promptForm').onsubmit=async event=>{event.preventDefault();await refreshEntitlement();if(!workAccess)return;const prompt=q('promptInput').value.trim();if(!prompt)return;if(!activeSession){await createSession();}if(!activeSession){toast(tr('Could not start an OpenCode session. Check the workspace runtime.','\u062a\u0639\u0630\u0631 \u0628\u062f\u0621 \u062c\u0644\u0633\u0629 OpenCode. \u062a\u062d\u0642\u0642 \u0645\u0646 \u062a\u0634\u063a\u064a\u0644 \u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644.'));return;}if(!agent.value||!q('providerSelect').value||!q('modelSelect').value){toast(tr('Connect a provider and select a model before sending.','\u0627\u0631\u0628\u0637 \u0645\u0632\u0648\u062f\u064b\u0627 \u0648\u0627\u062e\u062a\u0631 \u0646\u0645\u0648\u0630\u062c\u064b\u0627 \u0642\u0628\u0644 \u0627\u0644\u0625\u0631\u0633\u0627\u0644.'));updateSend();return;}q('sendMessage').disabled=true;try{await api('/api/sessions/'+activeSession.id+'/messages',{method:'POST',body:JSON.stringify({text:prompt,provider_id:q('providerSelect').value,model_id:q('modelSelect').value,agent_id:agent.value})});q('promptInput').value='';q('stopAgent').disabled=false;}catch(error){toast(error.message);updateSend();}};
  q('promptInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();q('promptForm').requestSubmit();}});
  async function openRepositoryPicker(){
    const dialog=document.createElement('dialog');dialog.className='workspace-repository-dialog';const close=btn('repositoryClose','Close','إغلاق',()=>dialog.close());dialog.append(title('Working repository / branch','مستودع العمل / الفرع'),close);
    const state=await api('/api/github/status');if(!state.connected){dialog.append(text('p','Connect GitHub in Settings to choose your repository.','اربط GitHub من الإعدادات لاختيار مستودعك.'),btn('repositoryConnect','Settings · GitHub','الإعدادات · GitHub',()=>{dialog.close();openConnections('github');}));}
    else{const repos=await api('/api/github/repositories'),form=document.createElement('form'),repository=document.createElement('select'),branch=document.createElement('select'),name=document.createElement('input');repository.id='workspaceRepository';branch.id='workspaceRemoteBranch';name.id='workspaceProjectName';repository.setAttribute('aria-label','Repository');branch.setAttribute('aria-label','Branch');name.setAttribute('aria-label','Project name');name.placeholder=tr('Project name','اسم المشروع');name.required=repository.required=branch.required=true;repository.add(new Option(tr('Choose repository','اختر مستودعًا'),''));for(const r of repos)repository.add(new Option(r.full_name,r.full_name));repository.onchange=async()=>{branch.replaceChildren();if(!repository.value)return;try{for(const b of await api('/api/github/branches?repository='+encodeURIComponent(repository.value)))branch.add(new Option(b.name,b.name));name.value=repository.value.split('/').pop();}catch(error){toast(error.message);}};const submit=text('button','Open new workspace','فتح مساحة عمل جديدة','button');submit.type='submit';form.append(repository,branch,name,submit);form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;try{const result=await api('/api/projects',{method:'POST',body:JSON.stringify({source_type:'github',repository:repository.value,branch:branch.value,project_name:name.value})});dialog.close();await openWorkspace(result.project,result.workspace);}catch(error){toast(error.message);}finally{submit.disabled=false;}};dialog.append(form);}
    document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
  }
  const refundPolicy=text('p','Subscription payments are non-refundable.','الاشتراكات غير قابلة لاسترداد المبلغ.','refund-policy');refundPolicy.id='subscriptionRefundPolicy';document.querySelector('#landing .pricing').append(refundPolicy);
  const prefs=applyPrefs;applyPrefs=()=>{prefs();for(const [node,en,ar] of texts){if(!node.firstChild)node.textContent=tr(en,ar);else if(node.firstChild.nodeType===3)node.firstChild.textContent=tr(en,ar);}q('homeSessionSearch').placeholder=tr('Search recent sessions…','ابحث في الجلسات الأخيرة…');renderEntitlement();};
  // The wordmark is a landing-page navigation control for every role.
  const brand=document.querySelector('#app-header .header-brand');if(brand){brand.setAttribute('role','button');brand.tabIndex=0;brand.setAttribute('aria-label','OpenCode Gateway — Home');brand.style.cursor='pointer';brand.onclick=()=>page('landing');brand.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();page('landing');}};}
  const paymentOrders=document.createElement('section');paymentOrders.id='clientPaymentOrders';document.querySelector('[data-client-panel=billing]').append(paymentOrders);
  const adminOrders=document.createElement('section');adminOrders.id='adminPaymentOrders';document.querySelector('[data-admin-panel=billing]').append(adminOrders);
  let paymentLoadCounter=0;
  async function loadPaymentOrders(platform=false){const host=platform?adminOrders:paymentOrders;const token=String(++paymentLoadCounter);host.dataset.paymentLoad=token;host.replaceChildren(title(platform?'Payment review':'Payment orders',platform?'مراجعة المدفوعات':'طلبات الدفع'));const list=await api(platform?'/api/billing/admin/orders':'/api/billing/orders');if(host.dataset.paymentLoad!==token)return;for(const order of list){const row=textElement('div','','manage-row');row.append(textElement('strong',order.plan_name+' · '+order.currency+' '+(order.amount_cents/100).toFixed(2)),textElement('span',(order.email||'')+' · '+order.status));if(order.payment_reference)row.append(textElement('small',order.payment_reference));if(platform&&order.status==='pending_review')row.append(btn('confirm-'+order.id,'Verify receipt / Activate','تأكيد الاستلام / التفعيل',async()=>{const reference=await window.requestInput(tr('After verifying the transfer was received, enter its receipt reference.','بعد التحقق من استلام التحويل، أدخل مرجع الاستلام.'));if(!reference)return;await api('/api/billing/admin/orders/'+order.id+'/confirm',{method:'POST',body:JSON.stringify({reference})});await loadPaymentOrders(true);}));if(!platform&&order.provider_environment&&!['paid','sandbox_paid'].includes(order.status))row.append(btn('capture-'+order.id,'Confirm PayPal payment','تأكيد دفع PayPal',async()=>{const verified=await api('/api/billing/orders/'+order.id+'/paypal/capture',{method:'POST'});await oldClientView('billing');await loadPaymentOrders();toast(verified.status==='sandbox_paid'?tr('Sandbox payment verified. Real subscription unchanged.','تم التحقق من الدفع التجريبي دون تفعيل اشتراك حقيقي.'):tr('Payment verified. Subscription active.','تم التحقق من الدفع وتفعيل الاشتراك.'));}));if(!platform&&order.status==='awaiting_payment')row.append(btn('resume-'+order.id,'Payment instructions','تعليمات الدفع',()=>beginCheckout(order.plan_id,order.method_id)));host.append(row);}if(!list.length)host.append(text('p','No payment orders yet.','لا توجد طلبات دفع بعد.'));}
  async function beginCheckout(planId,methodId){
    const [plans]=await Promise.all([api('/api/plans', {cache:'no-store'})]);
    const plan=plans.find(p=>p.id===planId);if(!plan)return toast(tr('Plan unavailable','الخطة غير متاحة'));
    const methods=await api('/api/billing/available-methods?plan_id='+encodeURIComponent(planId));
    const dialog=document.createElement('dialog');dialog.className='workspace-repository-dialog checkout-dialog';dialog.setAttribute('aria-label',tr('Subscription checkout','دفع الاشتراك'));
    dialog.append(title('Subscribe / Payment','الاشتراك / الدفع'),btn('checkoutClose','Close','إغلاق',()=>dialog.close()));
    const choices=textElement('div','','checkout-plans');for(const p of plans.filter(p=>p.active!==false)){
      const choiceLabel=(window.planDisplayName?window.planDisplayName(p):p.name)+' ? '+(window.planDisplayPrice?window.planDisplayPrice(p):(p.currency+' '+(p.price_cents/100).toFixed(2)))+' ? '+(window.planDisplayTerm?window.planDisplayTerm(p):(p.duration_days+' days'));const choice=btn('checkoutPlan-'+p.id,choiceLabel,choiceLabel,()=>{dialog.close();beginCheckout(p.id);});choice.setAttribute('aria-pressed',String(p.id===planId));choices.append(choice);
    }dialog.append(choices);
    const summary=textElement('section','','checkout-summary');summary.append(textElement('strong',window.planDisplayName?window.planDisplayName(plan):plan.name),text('span','Total','????????'),textElement('b',window.planDisplayPrice?window.planDisplayPrice(plan):(plan.currency+' '+(plan.price_cents/100).toFixed(2))),textElement('span',window.planDisplayTerm?window.planDisplayTerm(plan):(plan.duration_days+' days')));dialog.append(summary);
    const lead=text('p','Choose a payment method. Your access activates after receipt is verified.','اختر وسيلة دفع. يُفعّل الوصول بعد التحقق من الاستلام.','checkout-lead');dialog.append(lead);
    const select=document.createElement('select');select.id='checkoutMethod';select.hidden=true;const rows=textElement('fieldset','','checkout-methods');rows.append(text('legend','Payment method','وسيلة الدفع'));
    for(const method of methods){select.add(new Option(method.label,method.id));const label=textElement('label','','checkout-method');const radio=document.createElement('input');radio.type='radio';radio.name='payment-method';radio.value=method.id;radio.checked=method.id===(methodId||methods[0]?.id);const copy=textElement('span');copy.append(textElement('strong',method.label),textElement('small',method.details.checkout_mode==='paypal'?tr('PayPal / Card · verified checkout','PayPal / بطاقة · دفع موثّق'):method.details.checkout_mode==='link'?tr('Secure hosted checkout','دفع عبر صفحة مزود الدفع'):tr('Bank / wallet transfer','تحويل بنكي / محفظة')));label.append(radio,copy);rows.append(label);radio.onchange=()=>{select.value=radio.value;};}
    if(methodId&&methods.some(m=>m.id===methodId))select.value=methodId;
    const body=textElement('section','','checkout-receipt');body.setAttribute('aria-live','polite');
    const go=btn('createPaymentOrder','Next step','الخطوة التالية',async()=>{go.disabled=true;try{
      const result=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({plan_id:planId,method_id:select.value})});rows.hidden=true;choices.hidden=true;go.hidden=true;lead.hidden=true;
      if(result.automatic_processing){body.replaceChildren(text('p','Approve on PayPal, then confirm here. Access activates only after the completed payment is verified.','وافق على الدفع في PayPal ثم أكد هنا. يُفعّل الوصول بعد التحقق من اكتمال الدفع فقط.'));if(result.approval_url){const link=textElement('a',tr('Pay with PayPal / Card','الدفع عبر PayPal / البطاقة'),'button checkout-hosted-link');link.href=result.approval_url;link.target='_blank';link.rel='noopener noreferrer';body.append(link);}body.append(btn('confirmPayPalPayment','Confirm PayPal payment','تأكيد دفع PayPal',async()=>{const verified=await api('/api/billing/orders/'+result.order.id+'/paypal/capture',{method:'POST'});dialog.close();await oldClientView('billing');await loadPaymentOrders();toast(verified.status==='sandbox_paid'?tr('Sandbox payment verified. Real subscription unchanged.','تم التحقق من الدفع التجريبي دون تفعيل اشتراك حقيقي.'):tr('Payment verified. Subscription active.','تم التحقق من الدفع وتفعيل الاشتراك.'));}));return;}
      body.replaceChildren(textElement('strong',result.method.label));
      const labels={account_name:tr('Recipient','المستفيد'),account_reference:tr('Recipient account / address','حساب المستفيد / العنوان'),bank_name:tr('Bank','البنك'),currency:tr('Currency','العملة'),network:tr('Network','الشبكة'),instructions:tr('Instructions','التعليمات')};const details=document.createElement('dl');details.className='checkout-details';for(const [key,label] of Object.entries(labels)){const value=result.method.details[key];if(value)details.append(textElement('dt',label),textElement('dd',value));}body.append(details);
      if(result.payment_url){const link=textElement('a',tr('Continue to secure payment','المتابعة إلى الدفع الآمن'),'button checkout-hosted-link');link.href=result.payment_url;link.target='_blank';link.rel='noopener noreferrer';body.append(link,text('p','PayPal may offer debit or credit card checkout without signing in. Available methods are decided by the payment provider.','قد يتيح PayPal الدفع بالبطاقة دون تسجيل الدخول. مزود الدفع يحدد الوسائل المتاحة.'));}
      body.append(text('p','After paying, submit the receipt / transaction reference. Opening a link does not activate a subscription. Administration verifies receipt first.','بعد الدفع أرسل مرجع العملية / الإيصال. فتح الرابط لا يفعّل الاشتراك؛ تتحقق الإدارة من الاستلام أولاً.'));
      if(result.order.status==='awaiting_payment'){const form=document.createElement('form'),reference=document.createElement('input');form.dataset.paymentForm='customer';const label=text('label','Payment receipt reference','مرجع إيصال الدفع');label.htmlFor='paymentReference';reference.id='paymentReference';reference.required=true;reference.minLength=3;reference.maxLength=200;reference.autocomplete='off';const send=text('button','Submit payment reference','إرسال مرجع الدفع','button');send.type='submit';form.append(label,reference,send);form.onsubmit=async event=>{event.preventDefault();send.disabled=true;try{await api('/api/billing/orders/'+result.order.id+'/reference',{method:'PUT',body:JSON.stringify({reference:reference.value})});dialog.close();await oldClientView('billing');await loadPaymentOrders();toast(tr('Payment reference submitted for review.','أُرسل مرجع الدفع للمراجعة.'));}catch(error){toast(error.message);}finally{send.disabled=false;}};body.append(form);}else body.append(textElement('p',result.order.status));
    }catch(error){body.replaceChildren(textElement('p',error.message));}finally{go.disabled=false;}});go.disabled=!methods.length;
    if(!methods.length)dialog.append(text('p','No payment method is configured for this plan yet.','لم تُعدّ وسيلة دفع لهذه الخطة بعد.'));
    dialog.append(rows,select,go,body,textElement('small',tr('Payment for: ','الدفع لحساب: ')+currentUser.email),text('p','Subscription payments are non-refundable.','الاشتراكات غير قابلة لاسترداد المبلغ.','refund-policy'));document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();
  }
  window.beginCheckout=beginCheckout;
  authReady.then(async()=>{const params=new URLSearchParams(location.search);if(!params.has('payment_return')&&!params.has('payment_cancel'))return;if(!currentUser){page('authPage');return;}await window.openClientView('billing');if(params.has('payment_cancel'))toast(tr('Payment cancelled. No subscription activated.','تم إلغاء الدفع دون تفعيل الاشتراك.'));else toast(tr('Returned from PayPal. Confirm your payment in Payment orders.','عدت من PayPal. أكد الدفع من طلبات الدفع.'));history.replaceState(null,'',location.pathname+location.hash);}).catch(error=>toast(error.message));
  setInterval(async()=>{if(!currentUser||admin()||!document.querySelector('#workspacePage.active,#workspaceHomePage.active'))return;try{await refreshEntitlement();}catch(error){toast(error.message);}},30000);
  document.addEventListener('click',event=>{if(event.target.closest('#clientNav [data-client-view=billing]'))loadPaymentOrders().catch(e=>toast(e.message));if(event.target.closest('#adminNav [data-admin-view=billing]'))loadPaymentOrders(true).catch(e=>toast(e.message));});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden&&q('workspacePage').classList.contains('active'))refreshChoices();});
  const choicesObserver=new MutationObserver(()=>{if(q('workspacePage').classList.contains('active')&&activeWorkspace)refreshChoices();});choicesObserver.observe(q('workspacePage'),{attributes:true,attributeFilter:['class']});
  matchMedia('(max-width:1100px)').addEventListener('change',()=>{pane.classList.remove('open');overlay(false);});
  applyPrefs();
})();
