/* Workspace-first client interaction. All operational requests use Gateway APIs. */
(() => {
  window.workspaceFirstEnabled=true;
  const q=id=>document.getElementById(id),tr=(en,ar)=>lang==='ar'?ar:en;
  const admin=()=>['admin','owner'].includes(currentUser?.role);
  const texts=[];
  function text(tag,en,ar,cls){const node=textElement(tag,tr(en,ar),cls);texts.push([node,en,ar]);return node;}
  function btn(id,en,ar,action,cls='button ghost small'){const node=text('button',en,ar,cls);node.id=id;node.type='button';node.onclick=async()=>{try{await action();}catch(error){toast(error.message);}};return node;}
  function title(en,ar){return text('h2',en,ar);}
  const home=document.createElement('main');home.id='workspaceHomePage';home.className='page portal-page';
  home.innerHTML='<div class="workspace-home portal-content"><div class="work-home-heading"></div><div class="home-actions"></div><label class="session-search"><input id="homeSessionSearch" type="search"></label><section><h2 id="homeProjectsTitle"></h2><div id="homeProjects"></div></section><section><h2 id="homeSessionsTitle"></h2><div id="homeSessions"></div></section></div>';
  q('app-main').append(home);
  home.querySelector('.work-home-heading').append(text('span','YOUR WORKSPACE','مساحة عملك','eyebrow'),text('h1','What will you build today?','ماذا ستبني اليوم؟'),text('p','Open a project, continue a conversation, or start something new.','افتح مشروعًا، أكمل محادثة، أو ابدأ فكرة جديدة.','lead'));
  home.querySelector('.home-actions').append(btn('homeNewProject','New project','مشروع جديد',()=>page('onboarding'),'button'),btn('homeConnections','Settings · Connections','الإعدادات · الاتصالات',()=>openConnections()));
  texts.push([q('homeProjectsTitle'),'Projects / workspaces','المشاريع / مساحات العمل'],[q('homeSessionsTitle'),'Recent conversations','المحادثات الأخيرة']);
  q('homeSessionSearch').setAttribute('aria-label','Search sessions');
  const settings=document.createElement('main');settings.id='connectionsPage';settings.className='page portal-page';
  settings.innerHTML='<div class="portal-content connections-content"><div class="connections-heading"></div><div id="connectionsProviders"></div><div id="connectionsGithub"></div><div id="connectionsRuntime"></div></div>';
  q('app-main').append(settings);settings.querySelector('.connections-heading').append(text('h1','Settings · Connections','الإعدادات · الاتصالات'),text('p','Choose a provider and add its API key. After connection, its available models and agents appear in your workspace.','\u0627\u062e\u062a\u0631 \u0645\u0632\u0648\u0651\u062f\u064b\u0627 \u0648\u0623\u0636\u0641 \u0645\u0641\u062a\u0627\u062d API. \u0628\u0639\u062f \u0627\u0644\u0631\u0628\u0637\u060c \u0633\u062a\u0638\u0647\u0631 \u0646\u0645\u0627\u0630\u062c\u0647 \u0648\u0648\u0643\u0644\u0627\u0624\u0647 \u0641\u064a \u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644.','lead'),btn('connectionsReturn','Return to workspace','العودة لمساحة العمل',()=>activeWorkspace?page('workspacePage'):page('workspaceHomePage')));
  protectedPages.add('workspaceHomePage');protectedPages.add('connectionsPage');
  Object.assign(copy.en,{workspaceHome:'Workspace / Home',connectionsSettings:'Settings / Connections'});
  Object.assign(copy.ar,{workspaceHome:'مساحة العمل / الرئيسية',connectionsSettings:'الإعدادات / الاتصالات'});
  Object.assign(copy.en,{subscriptionNoRefund:'Subscription payments are non-refundable.',clientAccountLead:'Personal details and preferences.'});
  Object.assign(copy.ar,{subscriptionNoRefund:'الاشتراكات غير قابلة لاسترداد المبلغ.',clientAccountLead:'البيانات الشخصية والتفضيلات.'});
  function navButton(id,key,icon,action){const node=document.createElement('button');node.id=id;node.dataset.go=action;node.innerHTML='<svg class="nav-icon"><use href="'+icon+'"/></svg><span data-i18n="'+key+'">'+t(key)+'</span>';node.onclick=()=>page(action);return node;}
  q('clientNav').insertBefore(navButton('clientWorkspaceHome','workspaceHome','#icon-opencode','workspaceHomePage'),q('clientNav').querySelector('button'));
  q('clientNav').querySelector('[data-client-view=dashboard]')?.remove();
  q('clientNav').querySelector('[data-client-view=ai]')?.remove();q('clientNav').querySelector('[data-client-view=github]')?.remove();
  q('clientNav').append(navButton('clientConnections','connectionsSettings','#icon-settings','connectionsPage'));
  const oldClientView=window.openClientView;
  window.openClientView=name=>['ai','github'].includes(name)?openConnections(name==='ai'?'providers':'github'):oldClientView(name);
  q('clientNav').querySelectorAll('[data-client-view]').forEach(button=>button.onclick=()=>window.openClientView(button.dataset.clientView));
  q('adminNav').querySelectorAll('[data-admin-view]').forEach(button=>button.onclick=()=>window.openAdminView(button.dataset.adminView));
  async function loadHome(){
    const data=await api('/api/dashboard');const projects=q('homeProjects');projects.replaceChildren();
    for(const project of data.projects){for(const workspace of project.workspaces){const row=textElement('div','','home-project-row');row.append(textElement('strong',project.name),textElement('small',(project.repository||tr('Local project','مشروع محلي'))+' · '+workspace.status));row.append(btn('home-open-'+workspace.id,'Open workspace','فتح مساحة العمل',()=>openWorkspace(project,workspace)),btn('home-session-'+workspace.id,'New session','جلسة جديدة',async()=>{await openWorkspace(project,workspace);await createSession();}));projects.append(row);}}
    if(!projects.children.length)projects.append(text('p','No projects yet. Create your first workspace.','لا توجد مشاريع بعد. أنشئ مساحة عملك الأولى.','home-empty'));
    const sessions=q('homeSessions');sessions.replaceChildren();
    for(const session of data.recent_sessions){const project=data.projects.find(p=>p.workspaces.some(w=>w.id===session.workspace_id));const workspace=project?.workspaces.find(w=>w.id===session.workspace_id);if(!workspace)continue;const row=btn('home-recent-'+session.id,session.title,session.title,async()=>{await openWorkspace(project,workspace);await selectSession(session);},'home-session-row');row.append(textElement('small',project.name+' · '+session.status));row.dataset.search=(session.title+' '+project.name).toLowerCase();sessions.append(row);}
    if(!sessions.children.length)sessions.append(text('p','No conversations yet. Open a project and start a session.','لا توجد محادثات بعد. افتح مشروعًا وابدأ جلسة.','home-empty'));
    q('homeSessionSearch').placeholder=tr('Search recent sessions…','ابحث في الجلسات الأخيرة…');
    renderEntitlement();q('homeSessionSearch').oninput=()=>sessions.querySelectorAll('[data-search]').forEach(row=>row.hidden=!row.dataset.search.includes(q('homeSessionSearch').value.trim().toLowerCase()));
  }
  async function openConnections(focus){await page('connectionsPage');if(focus)q(focus==='github'?'connectionsGithub':'connectionsProviders').scrollIntoView({block:'start',behavior:'smooth'});}
  window.openConnections=openConnections;
  async function loadConnections(){
    try{await window.renderManagement(q('connectionsProviders'),'providers');}catch(error){q('connectionsProviders').append(textElement('p',error.message,'connection-error'));}
    const github=q('connectionsGithub');github.replaceChildren(title('GitHub account / authorization','حساب GitHub / التفويض'));
    const status=await api('/api/github/status');github.append(textElement('p',status.connected?(status.account_login||'GitHub'):tr('Not connected','غير متصل')));
    const authorize=btn('settingsAuthorizeGithub','Authorize GitHub','تفويض GitHub',()=>window.location.assign('/api/github/install'));authorize.disabled=!status.configured;github.append(authorize);
    if(status.connected)github.append(btn('settingsDisconnectGithub','Disconnect','إلغاء الربط',async()=>{await api('/api/github/disconnect',{method:'POST'});await loadConnections();}));
    github.append(text('p','Repository permissions and installation access are managed in GitHub authorization. Choose your working repository beside the prompt.','تُدار صلاحيات المستودعات والتثبيت عبر تفويض GitHub. اختر مستودع العمل بجوار محرر الطلب.'));
    const runtime=q('connectionsRuntime');runtime.replaceChildren(title('Runtime / Server','وقت التشغيل / الخادم'));const state=await api('/api/opencode/status');runtime.append(textElement('p',state.runtime_mode+' · '+(state.healthy?tr('Healthy','جاهز'):tr('Unavailable','غير متاح'))));
  }
  let workAccess=false,entitlement=null;
  const homeAccess=textElement('div','','access-notice');homeAccess.id='homeAccessState';home.querySelector('.work-home-heading').append(homeAccess);
  const workspaceAccess=textElement('div','','access-notice');workspaceAccess.id='workspaceAccessState';q('promptForm').before(workspaceAccess);
  function renderEntitlement(){if(!entitlement)return;const end=entitlement.access.ends_at,days=end?Math.max(0,Math.ceil((new Date(end)-Date.now())/86400000)):0;homeAccess.replaceChildren(textElement('span',workAccess?(entitlement.access.reason==='trial'?tr('Free trial · ','التجربة المجانية · '):tr('Subscription · ','الاشتراك · '))+days+' '+tr('days remaining','يوم متبقٍ'):tr('Your access has expired. Subscribe to continue.','انتهت مدة الوصول. اشترك للمتابعة.')));workspaceAccess.replaceChildren();workspaceAccess.hidden=workAccess;if(!workAccess){const subscribe=()=>window.openClientView('billing');homeAccess.append(btn('homeSubscribe','Subscribe / Renew','اشترك / جدّد',subscribe));workspaceAccess.append(textElement('span',tr('Read-only workspace. Subscribe to continue coding.','مساحة العمل للقراءة فقط. اشترك لمتابعة البرمجة.')),btn('workspaceSubscribe','Subscribe / Renew','اشترك / جدّد',subscribe));}q('homeNewProject').disabled=!workAccess;q('promptInput').disabled=!workAccess;document.querySelectorAll('#sessionSidebar .new-session,#homeProjects [id^=home-session-],#sessionList .session,#homeSessions [id^=home-recent-]').forEach(n=>n.disabled=!workAccess);if(!workAccess){q('sendMessage').disabled=true;q('commitButton').disabled=true;q('pushButton').disabled=true;}}
  async function refreshEntitlement(){if(!currentUser||admin())return;entitlement=await api('/api/billing/subscription');workAccess=entitlement.access.allowed;if(!workAccess){if(activeSession&&!q('stopAgent').disabled){try{await api('/api/sessions/'+activeSession.id+'/stop',{method:'POST'});}catch(error){toast(error.message);}q('stopAgent').disabled=true;}stopEvents();}renderEntitlement();}
  const previousPage=page;page=async function(id){await authReady;await interfaceReady;if(admin()&&['workspaceHomePage','connectionsPage'].includes(id))id='adminPage';if(currentUser&&!admin()&&['onboarding'].includes(id)){const state=await api('/api/billing/subscription');if(!state.access.allowed){stopEvents();await oldClientView('billing');toast(tr('Your 10-day trial has ended. Subscribe to continue.','انتهت تجربتك لمدة عشرة أيام. اشترك للمتابعة.'));return;}}await previousPage(id);if(!currentUser)return;if(!admin()&&['workspaceHomePage','workspacePage'].includes(id))await refreshEntitlement();if(!admin()&&id==='workspacePage'&&activeWorkspace)await refreshChoices();if(admin()){if(q('adminPage').classList.contains('active')&&document.querySelector('[data-admin-panel=billing].active'))await loadPaymentOrders(true);return;}if(q(id)?.classList.contains('active')){if(id==='workspaceHomePage')await loadHome();if(id==='connectionsPage')await loadConnections();}};
  const shell=document.querySelector('#workspacePage .workspace-shell'),center=shell.querySelector('.agent-column'),pane=q('sessionSidebar'),review=q('reviewPanel');
  shell.classList.add('workspace-first','chat-only');
  q('manageProviders')?.remove();
  const previousShow=showPage;showPage=function(id){if(id==='adminPage'&&!admin()){toast('Administrator access required');id=currentUser?'workspaceHomePage':'authPage';}if(admin()&&['workspaceHomePage','connectionsPage','workspacePage'].includes(id))id='adminPage';pane.classList.remove('open');overlay(false);previousShow(id);q('clientWorkspaceHome').classList.toggle('active',['workspaceHomePage','workspacePage'].includes(id));q('clientConnections').classList.toggle('active',id==='connectionsPage');if(['workspaceHomePage','workspacePage','connectionsPage'].includes(id))q('clientNav').querySelectorAll('[data-client-view]').forEach(n=>n.classList.remove('active'));};
  const projectbar=center.querySelector('.project-bar');projectbar.querySelector('.statuses').hidden=true;
  const context=textElement('div','','composer-context');q('promptForm').prepend(context);context.append(q('workspaceRepo'),q('workspaceBranch'));const gitState=text('span','GitHub: checking…','GitHub: جارٍ التحقق…');gitState.id='workspaceGithubState';context.append(gitState,q('runtimeStatus'));
  const controls=q('promptForm').lastElementChild;controls.classList.add('composer-controls');
  const agent=document.createElement('select');agent.id='agentSelect';agent.hidden=true;agent.setAttribute('aria-label','Agent');agent.title=tr('Agent','الوكيل');controls.insertBefore(agent,q('providerSelect'));
  const connect=btn('composerConnectProvider','Connect provider','ربط مزوّد',()=>openConnections('providers'));controls.insertBefore(connect,q('providerSelect'));
  q('providerSelect').setAttribute('aria-label','Provider');q('modelSelect').setAttribute('aria-label','Model');
  const attach=btn('attachFiles','＋','＋',()=>{},'icon');attach.disabled=true;attach.title=tr('Attachments are not available yet','المرفقات غير متاحة بعد');controls.prepend(attach);
  q('openTools').onclick=()=>window.openConnections('providers');q('openTools').title=tr('Open OpenCode provider and workspace setup','\u0641\u062a\u062d \u0625\u0639\u062f\u0627\u062f \u0645\u0632\u0648\u062f OpenCode \u0648\u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644');q('chatGithub').onclick=()=>openRepositoryPicker();
  const links=center.querySelector('.workspace-links');links?.remove();
  const toolbar=textElement('nav','','workbench-toolbar');toolbar.append(btn('toggleSessions','Sessions / Review','الجلسات / المراجعة',()=>togglePane()),btn('workspaceChat','Conversation','المحادثة',()=>{shell.classList.add('chat-only');shell.classList.remove('review-only');review.classList.remove('open');}));
  for(const [name,en,ar] of [['files','Files','الملفات'],['diff','Changes / Diff','التغييرات / الفروقات'],['logs','Activity','النشاط']])toolbar.append(btn('workspace'+name,en,ar,async()=>{shell.classList.remove('chat-only');shell.classList.add('review-only');review.classList.add('open');await tab(name);}));
  center.insertBefore(toolbar,projectbar.nextSibling);center.append(review);
  const heading=text('h3','Sessions / history','الجلسات / السجل');pane.insertBefore(heading,q('sessionList'));
  const search=document.createElement('input');search.id='workspaceSessionSearch';search.type='search';search.placeholder=tr('Search sessions','ابحث في الجلسات');search.setAttribute('aria-label','Search workspace sessions');pane.insertBefore(search,q('sessionList'));search.oninput=()=>q('sessionList').querySelectorAll('.session').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(search.value.toLowerCase()));
  const workflow=textElement('section','','workspace-activity');workflow.append(title('Workflow / Activity','سير العمل / النشاط'));const events=textElement('div');events.id='workspaceActivity';workflow.append(events);pane.insertBefore(workflow,pane.querySelector('.side-spacer'));
  const reviewActions=textElement('div','','pane-review-actions');for(const name of ['files','diff','logs'])reviewActions.append(btn('pane-'+name,...({files:['Files','الملفات'],diff:['Review / Changes','المراجعة / التغييرات'],logs:['Activity','النشاط']}[name]),()=>q('workspace'+name).click()));pane.insertBefore(reviewActions,workflow);
  const eventObserver=new MutationObserver(records=>{for(const record of records)for(const item of record.addedNodes)if(item.nodeType===1&&item.classList.contains('event-line')){events.append(item.cloneNode(true));while(events.children.length>30)events.firstChild.remove();}});eventObserver.observe(q('agentFeed'),{childList:true});
  function drawer(){return matchMedia('(max-width:1100px)').matches;}
  function closePane(){pane.classList.remove('open');if(!drawer())shell.classList.add('sessions-collapsed');overlay(false);}
  function togglePane(){if(drawer()){pane.classList.toggle('open');overlay(pane.classList.contains('open'));}else shell.classList.toggle('sessions-collapsed');}
  q('openSessions').onclick=togglePane;q('closeSessions').onclick=closePane;q('backdrop').addEventListener('click',()=>{pane.classList.remove('open');});
  q('reviewButton').onclick=()=>q('workspacefiles').click();q('closeReview').onclick=()=>q('workspaceChat').click();
  const oldRefreshGit=refreshGit;refreshGit=async()=>{await oldRefreshGit();q('manageProviders')?.remove();};
  let providers=[],chosenAgent='',chosenProvider='',chosenModel='',discovery=0;
  function updateSend(){q('sendMessage').disabled=!workAccess||!activeSession||!agent.value||!q('providerSelect').value||!q('modelSelect').value||!q('stopAgent').disabled;}
  async function refreshChoices(preferredProvider=''){
    if(!activeWorkspace||admin())return;if(!workAccess){agent.disabled=q('providerSelect').disabled=q('modelSelect').disabled=true;updateSend();return;}const workspaceId=activeWorkspace.id,stamp=++discovery;
    const result=await Promise.allSettled([api('/api/workspaces/'+workspaceId+'/providers'),api('/api/workspaces/'+workspaceId+'/agents')]);if(stamp!==discovery||activeWorkspace?.id!==workspaceId)return;
    providers=result[0].status==='fulfilled'?result[0].value:[];const connected=providers.filter(p=>p.connected),agents=result[1].status==='fulfilled'?result[1].value:[];
    q('providerSelect').replaceChildren(new Option(tr('Provider','المزوّد'),''));for(const p of connected)q('providerSelect').add(new Option(p.name,p.id));q('providerSelect').disabled=!connected.length;
    if(connected.some(p=>p.id===chosenProvider))q('providerSelect').value=chosenProvider;else if(connected.length===1)q('providerSelect').value=connected[0].id;
    agent.replaceChildren(new Option(tr('Agent','الوكيل'),''));for(const a of agents)agent.add(new Option(a.name,a.id));agent.disabled=!agents.length;agent.value=agents.some(a=>a.id===chosenAgent)?chosenAgent:(agents.find(a=>a.id==='build')?.id||agents[0]?.id||'');
    agent.hidden=!connected.length;chosenAgent=agent.value;
    connect.hidden=connected.length>0;
    if(connected.some(p=>p.id===preferredProvider)){chosenProvider=preferredProvider;q('providerSelect').value=preferredProvider;}
    q('providerSelect').onchange=()=>{chosenProvider=q('providerSelect').value;chosenModel='';models();};agent.onchange=()=>{chosenAgent=agent.value;updateSend();};q('modelSelect').onchange=()=>{chosenModel=q('modelSelect').value;updateSend();};models();
    if(!connected.length){q('runtimeStatus').textContent=result[0].status==='rejected'?tr('Runtime unavailable','وقت التشغيل غير متاح'):tr('Connect a provider to begin','اربط مزوّدًا للبدء');}
  }
  function models(){q('modelSelect').replaceChildren(new Option(tr('Model','النموذج'),''));const selected=providers.find(p=>p.id===q('providerSelect').value);for(const model of selected?.models||[])q('modelSelect').add(new Option(model.name,model.id));q('modelSelect').disabled=!selected;q('modelSelect').value=selected?.models.some(m=>m.id===chosenModel)?chosenModel:(selected?.models[0]?.id||'');chosenModel=q('modelSelect').value;updateSend();}
  window.refreshWorkspaceChoices=refreshChoices;
  const originalWorkspace=openWorkspace;openWorkspace=async function(project,workspace){if(admin()){await page('adminPage');return;}chosenAgent=chosenProvider=chosenModel='';shell.classList.add('chat-only');shell.classList.remove('review-only');events.replaceChildren();await originalWorkspace(project,workspace);await refreshChoices();const state=await api('/api/github/status');gitState.textContent=state.connected?'GitHub · '+(state.account_login||tr('Connected','متصل')):tr('GitHub · Not connected','GitHub · غير متصل');q('chatGithub').title=gitState.textContent;renderEntitlement();};
  const originalSession=selectSession;selectSession=async function(session){if(!workAccess){toast(tr('Subscribe to resume this conversation.','اشترك لاستئناف هذه المحادثة.'));return;}await originalSession(session);await refreshChoices();};
  async function createSession(){if(!activeWorkspace)return;await refreshEntitlement();if(!workAccess)return;const b=pane.querySelector('.new-session');b.disabled=true;try{const row=await api('/api/workspaces/'+activeWorkspace.id+'/sessions',{method:'POST',body:JSON.stringify({title:tr('New session','جلسة جديدة')})});await refreshSessions();q('workspaceChat').click();await selectSession(row);}catch(error){toast(error.message);q('runtimeStatus').textContent=tr('OpenCode unavailable','OpenCode غير متاح');}finally{b.disabled=!workAccess;}}
  pane.querySelector('.new-session').onclick=createSession;
  q('promptForm').onsubmit=async event=>{event.preventDefault();await refreshEntitlement();if(!workAccess)return;const prompt=q('promptInput').value.trim();if(!prompt)return;if(!activeSession){await createSession();}if(!activeSession){toast(tr('Could not start an OpenCode session. Check the workspace runtime.','\u062a\u0639\u0630\u0631 \u0628\u062f\u0621 \u062c\u0644\u0633\u0629 OpenCode. \u062a\u062d\u0642\u0642 \u0645\u0646 \u062a\u0634\u063a\u064a\u0644 \u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644.'));return;}if(!agent.value||!q('providerSelect').value||!q('modelSelect').value){toast(tr('Connect a provider and select a model before sending.','\u0627\u0631\u0628\u0637 \u0645\u0632\u0648\u062f\u064b\u0627 \u0648\u0627\u062e\u062a\u0631 \u0646\u0645\u0648\u0630\u062c\u064b\u0627 \u0642\u0628\u0644 \u0627\u0644\u0625\u0631\u0633\u0627\u0644.'));updateSend();return;}q('sendMessage').disabled=true;try{await api('/api/sessions/'+activeSession.id+'/messages',{method:'POST',body:JSON.stringify({text:prompt,provider_id:q('providerSelect').value,model_id:q('modelSelect').value,agent_id:agent.value})});q('promptInput').value='';q('stopAgent').disabled=false;}catch(error){toast(error.message);updateSend();}};
  q('promptInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();q('promptForm').requestSubmit();}});
  async function openRepositoryPicker(){
    const dialog=document.createElement('dialog');dialog.className='workspace-repository-dialog';const close=btn('repositoryClose','Close','إغلاق',()=>dialog.close());dialog.append(title('Working repository / branch','مستودع العمل / الفرع'),close);
    const state=await api('/api/github/status');if(!state.connected){dialog.append(text('p','Connect GitHub in Settings to choose your repository.','اربط GitHub من الإعدادات لاختيار مستودعك.'),btn('repositoryConnect','Settings · GitHub','الإعدادات · GitHub',()=>{dialog.close();openConnections('github');}));}
    else{const repos=await api('/api/github/repositories'),form=document.createElement('form'),repository=document.createElement('select'),branch=document.createElement('select'),name=document.createElement('input');repository.id='workspaceRepository';branch.id='workspaceRemoteBranch';name.id='workspaceProjectName';repository.setAttribute('aria-label','Repository');branch.setAttribute('aria-label','Branch');name.setAttribute('aria-label','Project name');name.placeholder=tr('Project name','اسم المشروع');name.required=repository.required=branch.required=true;repository.add(new Option(tr('Choose repository','اختر مستودعًا'),''));for(const r of repos)repository.add(new Option(r.full_name,r.full_name));repository.onchange=async()=>{branch.replaceChildren();if(!repository.value)return;try{for(const b of await api('/api/github/branches?repository='+encodeURIComponent(repository.value)))branch.add(new Option(b.name,b.name));name.value=repository.value.split('/').pop();}catch(error){toast(error.message);}};const submit=text('button','Open new workspace','فتح مساحة عمل جديدة','button');submit.type='submit';form.append(repository,branch,name,submit);form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;try{const result=await api('/api/projects',{method:'POST',body:JSON.stringify({source_type:'github',repository:repository.value,branch:branch.value,project_name:name.value})});dialog.close();await openWorkspace(result.project,result.workspace);}catch(error){toast(error.message);}finally{submit.disabled=false;}};dialog.append(form);}
    document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
  }
  const refundPolicy=text('p','Subscription payments are non-refundable.','الاشتراكات غير قابلة لاسترداد المبلغ.','refund-policy');refundPolicy.id='subscriptionRefundPolicy';document.querySelector('#landing .pricing').append(refundPolicy);
  const prefs=applyPrefs;applyPrefs=()=>{prefs();for(const [node,en,ar] of texts){if(!node.firstChild)node.textContent=tr(en,ar);else if(node.firstChild.nodeType===3)node.firstChild.textContent=tr(en,ar);}q('homeSessionSearch').placeholder=tr('Search recent sessions…','ابحث في الجلسات الأخيرة…');renderEntitlement();};
  // The wordmark is a landing-page navigation control for every role.
  const brand=document.querySelector('#app-header .header-brand');if(brand){brand.setAttribute('role','button');brand.tabIndex=0;brand.setAttribute('aria-label','OpenCode Gateway — Home');brand.style.cursor='pointer';brand.onclick=()=>page('landing');brand.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();page('landing');}};}
  const paymentOrders=document.createElement('section');paymentOrders.id='clientPaymentOrders';document.querySelector('[data-client-panel=billing]').append(paymentOrders);
  const adminOrders=document.createElement('section');adminOrders.id='adminPaymentOrders';document.querySelector('[data-admin-panel=billing]').append(adminOrders);
  let paymentLoadCounter=0;
  async function loadPaymentOrders(platform=false){
    const host=platform?adminOrders:paymentOrders;const token=String(++paymentLoadCounter);host.dataset.paymentLoad=token;
    host.replaceChildren(title(platform?'Payment review':'Payment orders',platform?'مراجعة المدفوعات':'طلبات الدفع'));
    const list=await api(platform?'/api/billing/admin/orders':'/api/billing/orders');
    if(host.dataset.paymentLoad!==token)return;
    const ACTION_ICONS={view:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2.06 12.35a1 1 0 0 1 0-.7C3.42 8.1 7.22 5 12 5s8.58 3.1 9.94 6.65a1 1 0 0 1 0 .7C20.58 15.9 16.78 19 12 19s-8.58-3.1-9.94-6.65Z"/><circle cx="12" cy="12" r="3"/></svg>',resume:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.83 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/></svg>',cancel:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>',remove:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2m3 0v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/></svg>',confirm:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>',reject:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="m15 9-6 6M9 9l6 6"/></svg>'};
    const act=(id,icon,label,action)=>{const b=textElement('button','','icon-btn');b.id=id;b.type='button';b.title=label;b.setAttribute('aria-label',label);b.innerHTML=icon;b.onclick=async()=>{b.disabled=true;try{await action();}catch(error){toast(error.message)}finally{b.disabled=false;}};return b;};
    for(const order of list){
      const row=textElement('div','','manage-row');
      row.append(textElement('strong',order.plan_name+' · '+order.currency+' '+(order.amount_cents/100).toFixed(2)),textElement('span',(order.email||'')+' · '+order.status));
      if(order.payment_reference)row.append(textElement('small',order.payment_reference));
      if(order.sender_name)row.append(textElement('small',tr('Sender: ','المرسل: ')+order.sender_name));
      if(order.sender_email)row.append(textElement('small',order.sender_email));
      if(order.sender_bank)row.append(textElement('small',tr('From bank: ','البنك المرسل: ')+order.sender_bank));
      if(order.sender_account)row.append(textElement('small',tr('From account: ','الحساب المرسل: ')+order.sender_account));
      if(order.payer_name)row.append(textElement('small',tr('Payer: ','الدافع: ')+order.payer_name));
      if(order.transfer_date)row.append(textElement('small',order.transfer_date));
      if(order.amount_sent_cents)row.append(textElement('small',tr('Sent: ','المُرسل: ')+(order.amount_sent_cents/100).toFixed(2)+' '+order.currency));
      if(order.billing_note)row.append(textElement('small',order.billing_note));
      if(order.reject_reason)row.append(textElement('small',tr('Rejected: ','مرفوض: ')+order.reject_reason));
      const actions=textElement('div','','manage-actions');
      if(order.has_receipt){const rl=textElement('a','','icon-btn');rl.href='/api/billing/orders/'+order.id+'/receipt';rl.target='_blank';rl.rel='noopener noreferrer';rl.title=tr('View receipt','عرض الإيصال');rl.setAttribute('aria-label',rl.title);rl.innerHTML=ACTION_ICONS.view;actions.append(rl);}
      if(platform&&order.status==='pending_review'){
        actions.append(act('confirm-'+order.id,ACTION_ICONS.confirm,tr('Verify receipt / Activate','تأكيد الاستلام / التفعيل'),async()=>{const reference=await window.requestInput(tr('After verifying the transfer was received, enter its receipt reference.','بعد التحقق من استلام التحويل، أدخل مرجع الاستلام.'));if(!reference)return;await api('/api/billing/admin/orders/'+order.id+'/confirm',{method:'POST',body:JSON.stringify({reference})});await loadPaymentOrders(true);}));
        actions.append(act('reject-'+order.id,ACTION_ICONS.reject,tr('Reject','رفض'),async()=>{const reason=await window.requestInput(tr('Rejection reason','سبب الرفض'));if(!reason?.trim())return;await api('/api/billing/admin/orders/'+order.id+'/reject',{method:'POST',body:JSON.stringify({reason:reason.trim()})});await loadPaymentOrders(true);}));
      }
      if(!platform&&order.provider_environment&&!['paid','sandbox_paid'].includes(order.status))actions.append(act('capture-'+order.id,ACTION_ICONS.confirm,tr('Confirm PayPal payment','تأكيد دفع PayPal'),async()=>{const verified=await api('/api/billing/orders/'+order.id+'/paypal/capture',{method:'POST'});await oldClientView('billing');await loadPaymentOrders();toast(verified.status==='sandbox_paid'?tr('Sandbox payment verified. Real subscription unchanged.','تم التحقق من الدفع التجريبي دون تفعيل اشتراك حقيقي.'):tr('Payment verified. Subscription active.','تم التحقق من الدفع وتفعيل الاشتراك.'));}));
      if(!platform&&order.status==='awaiting_payment')actions.append(act('resume-'+order.id,ACTION_ICONS.resume,tr('Payment instructions','تعليمات الدفع'),()=>beginCheckout(order.plan_id,order.method_id)));
      if(!platform&&['awaiting_payment','pending_review'].includes(order.status))actions.append(act('cancel-'+order.id,ACTION_ICONS.cancel,tr('Cancel payment','إلغاء الدفع'),async()=>{if(!await window.confirmAction(tr('Cancel this payment request?','إلغاء طلب الدفع هذا؟')))return;await api('/api/billing/orders/'+order.id+'/cancel',{method:'POST'});await loadPaymentOrders();}));
      if(!platform&&['failed','cancelled','rejected'].includes(order.status))actions.append(act('remove-'+order.id,ACTION_ICONS.remove,tr('Remove from history','حذف من السجل'),async()=>{if(!await window.confirmAction(tr('Remove this payment from your history?','حذف هذا الدفع من سجلك؟')))return;await api('/api/billing/orders/'+order.id,{method:'DELETE'});await loadPaymentOrders();}));
      if(actions.children.length)row.append(actions);
      host.append(row);
    }
    if(!list.length)host.append(text('p',platform?tr('No payments to review','لا توجد مدفوعات للمراجعة'):tr('No payments yet. Successful payments stay here as records.','لا توجد مدفوعات بعد. تبقى المدفوعات الناجحة هنا كسجلات.')));
  }
  async function beginCheckout(planId,methodId){
    const [plans]=await Promise.all([api('/api/plans',{cache:'no-store'})]);
    const plan=plans.find(p=>p.id===planId);if(!plan)return toast(tr('Plan unavailable','الخطة غير متاحة'));
    const methods=await api('/api/billing/available-methods?plan_id='+encodeURIComponent(planId)+'&include_unavailable=true');
    const reasonCopy={provider_not_connected:tr('Provider is not connected','المزود غير متصل'),processor_not_connected:tr('Payment processor is not connected','معالج الدفع غير متصل'),details_not_configured:tr('Receiving details are not configured','بيانات الاستلام غير مهيأة')};const PAY_ICONS={paypal:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 5.8h5.9c2 0 3.3 1.2 3.1 3-.3 2.3-2.1 3.8-4.4 3.8H9.4L8.4 18h-2.6l1-6.4H5L7 5.8Z"/><path d="m12.6 8.6 1.4 1.2c1.8-1.2 4-.3 4.5 1.9.5 2.3-1.2 4.2-3.4 4.2h-1.7l-.5 3.1h-2.4l1.2-7.4h1.6"/></svg>',googlepay:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12a7 7 0 1 1-2.1-4.9"/><path d="M18.2 7.5H11.6"/><path d="M19.6 8.2 17 11.2"/></svg>',binance:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"><path d="M12 3.5 19.5 7.8v8.4L12 20.5l-7.5-4.3V7.8L12 3.5Z"/><path d="M12 8.8 15 10.5v3L12 15.2 9 13.5v-3l3-1.7Z"/><path d="M9.5 8.5h5"/></svg>',bank:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M3 10h18M5 10l7-6 7 6M6.5 14h1.8v3.5H6.5Zm4.6 0h1.8v3.5h-1.8Zm4.6 0h1.8v3.5h-1.8Z"/></svg>',wallet:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1H7a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-6a1 1 0 0 0-1-1h-4m-6-5h6"/></svg>'};const payIcon=kind=>{const s=document.createElement('span');s.className='pay-icon';s.setAttribute('aria-hidden','true');s.innerHTML=PAY_ICONS[kind]||PAY_ICONS.wallet;return s;};
    const dialog=document.createElement('dialog');dialog.className='workspace-repository-dialog checkout-dialog';dialog.setAttribute('aria-label',tr('Subscription checkout','دفع الاشتراك'));
    dialog.append(title('Subscribe / Payment','الاشتراك / الدفع'),btn('checkoutClose','Close','إغلاق',()=>dialog.close()));
    const choices=textElement('div','','checkout-plans');for(const p of plans.filter(p=>p.active!==false)){
      const choiceLabel=(window.planDisplayName?window.planDisplayName(p):p.name)+' · '+(window.planDisplayPrice?window.planDisplayPrice(p):(p.currency+' '+(p.price_cents/100).toFixed(2)))+' · '+(window.planDisplayTerm?window.planDisplayTerm(p):(p.duration_days+' days'));const choice=btn('checkoutPlan-'+p.id,choiceLabel,choiceLabel,()=>{dialog.close();beginCheckout(p.id);});choice.setAttribute('aria-pressed',String(p.id===planId));choices.append(choice);
    }dialog.append(choices);
    const summary=textElement('section','','checkout-summary');summary.append(textElement('strong',window.planDisplayName?window.planDisplayName(plan):plan.name),text('span','Total','الإجمالي'),textElement('b',window.planDisplayPrice?window.planDisplayPrice(plan):(plan.currency+' '+(plan.price_cents/100).toFixed(2))),textElement('span',window.planDisplayTerm?window.planDisplayTerm(plan):(plan.duration_days+' days')));dialog.append(summary);
    dialog.append(text('p','Choose a payment method. Your access activates after receipt is verified.','اختر وسيلة دفع. يُفعّل الوصول بعد التحقق من الاستلام.','checkout-lead'));
    const select=document.createElement('select');select.id='checkoutMethod';select.hidden=true;
    const noteWrap=text('label','Billing note (optional)','ملاحظة دفع (اختياري)');noteWrap.htmlFor='checkoutNote';const noteInput=document.createElement('input');noteInput.id='checkoutNote';noteInput.maxLength=500;noteInput.autocomplete='off';noteWrap.append(noteInput);
    const rows=textElement('fieldset','','checkout-methods');rows.append(text('legend','Payment method','وسيلة الدفع'));
    for(const method of methods){select.add(new Option(method.label,method.id));const label=textElement('label','','checkout-method');const radio=document.createElement('input');radio.type='radio';radio.name='payment-method';radio.value=method.id;radio.checked=method.id===(methodId||methods[0]?.id);const cardName=textElement('strong',method.label);cardName.prepend(payIcon(method.kind));const baseSub=method.details.checkout_mode==='paypal'?tr('PayPal · official checkout · card / PayPal account','PayPal · دفع رسمي · بطاقة / حساب PayPal'):method.details.checkout_mode==='link'?(method.kind==='googlepay'?tr('Google Pay · hosted by your payment processor','Google Pay · عبر مزوّد الدفع'):tr('Secure hosted checkout','دفع عبر صفحة مزود الدفع')):(method.kind==='binance'?tr('Binance Pay · USDT transfer','Binance Pay · تحويل USDT'):(method.kind==='bank'?tr('Bank transfer','تحويل بنكي'):tr('Wallet transfer','تحويل محفظة')));const copy=textElement('span');copy.append(cardName,textElement('small',method.available?baseSub:tr('Not connected','غير متصل')+' · '+(reasonCopy[method.available_reason]||'')));label.append(radio,copy);rows.append(label);radio.onchange=()=>{select.value=radio.value;};}
    if(methodId&&methods.some(m=>m.id===methodId))select.value=methodId;
    const body=textElement('section','','checkout-receipt');body.setAttribute('aria-live','polite');
    const showError=error=>body.replaceChildren(textElement('p',error.message||String(error),'api-message show error'));
    const renderProviderForm=method=>{
      const dl=document.createElement('dl');dl.className='checkout-details';
      for(const [label,value] of [[tr('Plan','الخطة'),plan.name],[tr('Amount','المبلغ'),(plan.price_cents/100).toFixed(2)],[tr('Currency','العملة'),plan.currency]]){dl.append(textElement('dt',label),textElement('dd',String(value)));}
      body.replaceChildren(dl);const phead=textElement('strong',method.label);phead.prepend(payIcon(method.kind));body.prepend(phead);
      const pfield=(labelText,id,type,extra)=>{const wrap=text('label',labelText,labelText);wrap.htmlFor=id;const inp=document.createElement('input');inp.id=id;inp.type=type;inp.required=true;Object.assign(inp,extra||{});wrap.append(inp);body.append(wrap);return inp;};
      const payerName=pfield(tr('Your full name','اسمك الكامل'),'payerName','text',{maxLength:150,autocomplete:'off'});
      const payerEmail=pfield(tr('Your email','بريدك الإلكتروني'),'payerEmail','email',{maxLength:254,autocomplete:'off'});
      const payerCountry=pfield(tr('Your country','دولتك'),'payerCountry','text',{maxLength:80,autocomplete:'off'});
      const go2=textElement('button',method.kind==='googlepay'?tr('Pay with Google Pay','الدفع عبر Google Pay'):tr('Continue to PayPal','المتابعة إلى PayPal'),'button checkout-hosted-link');go2.type='button';
      if(!method.available){const embedNote=method.details.checkout_mode==='paypal'?tr('The official PayPal buttons are already embedded in this form. They appear here automatically once the PayPal merchant credentials are configured on the server; card number, expiry and CVV are then entered on the PayPal hosted page only.','أزرار PayPal الرسمية مدمجة في هذا النموذج، وستظهر هنا تلقائيًا فور تهيئة بيانات تاجر PayPal على الخادم. تُدخل بيانات البطاقة في صفحة PayPal المستضافة فقط.'):tr('The Google Pay payment sheet is opened by the configured payment processor. It appears once a real processor checkout link is configured on the server.','نافذة الدفع Google Pay يفتحها مزوّد الدفع المهيأ، وستظهر فور تهيئة رابط دفع حقيقي على الخادم.');body.append(text('p',(reasonCopy[method.available_reason]||tr('Not connected','غير متصل'))+' — '+tr('the provider connection is checked when you continue.','يتم التحقق من اتصال المزوّد عند المتابعة.'),(reasonCopy[method.available_reason]||tr('Not connected','غير متصل'))+' — '+tr('the provider connection is checked when you continue.','يتم التحقق من اتصال المزوّد عند المتابعة.'),'checkout-lead'),text('p',embedNote,embedNote,'checkout-lead'));}
      body.append(go2);
      go2.onclick=async()=>{go2.disabled=true;try{
        const result=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({plan_id:planId,method_id:method.id,billing_note:noteInput.value.trim(),payer_name:payerName.value.trim(),payer_email:payerEmail.value.trim(),payer_country:payerCountry.value.trim()})});
        if(result.automatic_processing){
          body.replaceChildren(dl,text('p','Pay through the official PayPal checkout. Access activates only after the completed payment is verified.','ادفع عبر صفحة PayPal الرسمية. يُفعّل الوصول بعد التحقق من اكتمال الدفع فقط.'));
          let ppStatus=null;try{ppStatus=await api('/api/billing/paypal/status')}catch(error){ppStatus=null}
          if(ppStatus&&ppStatus.configured&&ppStatus.client_id&&result.order.provider_order_id){
            const host=textElement('div');host.id='paypalButtonHost';body.append(host);
            const loadPp=()=>new Promise((resolve,reject)=>{if(window.paypal)return resolve(window.paypal);const s=document.createElement('script');s.src='https://www.paypal.com/sdk/js?client-id='+encodeURIComponent(ppStatus.client_id)+'&currency='+encodeURIComponent(result.order.currency)+'&intent=capture&components=buttons';s.onload=()=>resolve(window.paypal);s.onerror=()=>reject(new Error('paypal-sdk'));document.head.append(s);});
            loadPp().then(pp=>{pp.Buttons({style:{layout:'vertical'},createOrder:()=>result.order.provider_order_id,onApprove:async()=>{const verified=await api('/api/billing/orders/'+result.order.id+'/paypal/capture',{method:'POST'});dialog.close();await oldClientView('billing');await loadPaymentOrders();toast(verified.status==='sandbox_paid'?tr('Sandbox payment verified. Real subscription unchanged.','تم التحقق من الدفع التجريبي دون تفعيل اشتراك حقيقي.'):tr('Payment verified. Subscription active.','تم التحقق من الدفع وتفعيل الاشتراك.'));},onCancel:()=>toast(tr('Payment cancelled. No subscription activated.','تم إلغاء الدفع دون تفعيل الاشتراك.')),onError:()=>toast(tr('PayPal could not complete this payment. No subscription activated.','تعذر إتمام الدفع عبر PayPal دون تفعيل الاشتراك.'))}).render('#paypalButtonHost');}).catch(()=>{if(result.approval_url)window.location.assign(result.approval_url);});
          }else if(result.approval_url)window.location.assign(result.approval_url);
          body.append(btn('confirmPayPalPayment','Confirm PayPal payment','تأكيد دفع PayPal',async()=>{const verified=await api('/api/billing/orders/'+result.order.id+'/paypal/capture',{method:'POST'});dialog.close();await oldClientView('billing');await loadPaymentOrders();toast(verified.status==='sandbox_paid'?tr('Sandbox payment verified. Real subscription unchanged.','تم التحقق من الدفع التجريبي دون تفعيل اشتراك حقيقي.'):tr('Payment verified. Subscription active.','تم التحقق من الدفع وتفعيل الاشتراك.'));}));
        }else if(result.payment_url){
          const link=textElement('a',tr('Open the payment provider page','فتح صفحة مزود الدفع'),'button checkout-hosted-link');link.href=result.payment_url;link.target='_blank';link.rel='noopener noreferrer';const pvNote=tr('Complete payment on the provider page, then submit your reference for verification.','أكمل الدفع في صفحة المزود، ثم أرسل مرجعك للتحقق.');body.append(link,text('p',pvNote,pvNote,'checkout-lead'));
        }
      }catch(error){showError(error);}finally{go2.disabled=false;}};
    };
    const renderManualForm=method=>{
      const mhead=textElement('strong',method.label);mhead.prepend(payIcon(method.kind));body.replaceChildren(mhead);
      if(method.kind==='bank')body.append(text('p','Transfer to the account holder below, then upload your proof of transfer.','حوّل إلى صاحب الحساب أدناه، ثم ارفع إثبات التحويل.','checkout-lead'));
      const labels={account_name:tr('Recipient','المستفيد'),account_reference:tr('Recipient account / address','حساب المستفيد / العنوان'),iban:tr('IBAN','الآيبان'),branch:tr('Branch','الفرع'),bank_name:tr('Bank','البنك'),currency:tr('Currency','العملة'),network:tr('Network','الشبكة'),instructions:tr('Instructions','التعليمات')};
      if(method.kind==='binance'){labels.account_reference=tr('Binance wallet address or username','عنوان محفظة Binance أو اسم المستخدم');const bAmt=tr('Amount: ','المبلغ: ')+'$'+((plan.price_cents/100).toFixed(2))+' USD',bUsdt=tr('USDT to pay (fixed 1 USD = 1 USDT parity): ','مبلغ USDT المطلوب (تعادل ثابت 1 دولار = 1 USDT): ')+((plan.price_cents/100).toFixed(2))+' USDT',bSend=tr('Send USDT from your Binance account to the address above, then attach the transfer screenshot below.','أرسل USDT من حساب Binance الخاص بك إلى العنوان أعلاه، ثم أرفق لقطة شاشة للتحويل أدناه.');body.append(text('p',bAmt,bAmt),text('p',bUsdt,bUsdt),text('p',bSend,bSend,'checkout-lead'));}
      const details=document.createElement('dl');details.className='checkout-details';for(const [key,label] of Object.entries(labels)){const value=method.details[key];if(value)details.append(textElement('dt',label),textElement('dd',value));}body.append(details);
      const form=document.createElement('form');form.dataset.paymentForm='customer';
      const mkField=(labelText,id,type,extra)=>{const wrap=text('label',labelText,labelText);wrap.htmlFor=id;const inp=document.createElement('input');inp.id=id;inp.type=type;inp.required=true;Object.assign(inp,extra||{});wrap.append(inp);form.append(wrap);return inp;};
      const sender=mkField(tr('Sender name (account holder)','اسم المُرسل (صاحب الحساب)'),'paymentSender','text',{maxLength:150,autocomplete:'off'});
      const senderEmail=mkField(tr('Sender email','بريد المُرسل'),'paymentSenderEmail','email',{maxLength:254,autocomplete:'off'});
      const senderBank=mkField(tr('Sender bank name','اسم بنك المُرسل'),'paymentSenderBank','text',{maxLength:150,autocomplete:'off'});
      const senderAccount=mkField(tr('Sender account number / IBAN','رقم حساب المُرسل / الآيبان'),'paymentSenderAccount','text',{maxLength:200,autocomplete:'off'});
      const reference=mkField(tr('Transaction / reference number','رقم العملية / المرجع'),'paymentReference','text',{minLength:3,maxLength:200,autocomplete:'off'});
      const tdate=mkField(tr('Transfer date','تاريخ التحويل'),'paymentDate','date',{});
      const sent=mkField(tr('Amount sent','المبلغ المُرسل'),'paymentSent','number',{min:'0.01',step:'0.01'});
      const fileWrap=text('label','Receipt screenshot (PNG, JPEG, WebP or PDF, up to 5 MB)','صورة الإيصال (PNG أو JPEG أو WebP أو PDF حتى 5 ميجابايت)');fileWrap.htmlFor='paymentReceipt';const receipt=document.createElement('input');receipt.id='paymentReceipt';receipt.type='file';receipt.required=true;receipt.accept='.png,.jpg,.jpeg,.webp,.pdf';fileWrap.append(receipt);form.append(fileWrap);
      const send=text('button','Submit payment for review','إرسال الدفع للمراجعة','button');send.type='submit';form.append(send);
      form.onsubmit=async event=>{event.preventDefault();send.disabled=true;try{
        if(!receipt.files.length)throw new Error(tr('Attach the receipt screenshot first.','أرفق صورة الإيصال أولاً.'));
        const result=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({plan_id:planId,method_id:method.id,billing_note:noteInput.value.trim()})});
        const fd=new FormData();fd.append('file',receipt.files[0]);
        const up=await fetch('/api/billing/orders/'+result.order.id+'/receipt',{method:'POST',body:fd,credentials:'same-origin'});
        if(!up.ok)throw new Error((await up.json().catch(()=>({}))).detail||'Receipt upload failed');
        await api('/api/billing/orders/'+result.order.id+'/reference',{method:'PUT',body:JSON.stringify({reference:reference.value,sender_name:sender.value,sender_email:senderEmail.value,sender_bank:senderBank.value,sender_account:senderAccount.value,transfer_date:tdate.value,amount_sent_cents:Math.round(Number(sent.value)*100)})});
        dialog.close();await oldClientView('billing');await loadPaymentOrders();
        toast(tr('Payment submitted. Status: pending verification.','أُرسل الدفع. الحالة: بانتظار التحقق.'));
      }catch(error){showError(error);}finally{send.disabled=false;}};
      body.append(form);
    };
    const go=btn('createPaymentOrder','Next step','الخطوة التالية',async()=>{
      const method=methods.find(m=>m.id===select.value);
      if(!method){toast(tr('Choose a payment method first.','اختر وسيلة الدفع أولاً.'));return;}
      rows.hidden=true;choices.hidden=true;go.hidden=true;noteWrap.hidden=true;
      if(method.details.checkout_mode==='paypal'||method.details.checkout_mode==='link')renderProviderForm(method);
      else renderManualForm(method);
    });go.disabled=!methods.length;
    if(!methods.length)dialog.append(text('p','No payment method is configured for this plan yet.','لم تُعدّ وسيلة دفع لهذه الخطة بعد.'));
    dialog.append(rows,select,noteWrap,go,body,textElement('small',tr('Payment for: ','الدفع لحساب: ')+currentUser.email),text('p','Subscription payments are non-refundable.','الاشتراكات غير قابلة لاسترداد المبلغ.','refund-policy'));
    document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();
  }
  window.beginCheckout=beginCheckout;
  authReady.then(async()=>{const params=new URLSearchParams(location.search);const ret=params.get('payment_return'),cancel=params.get('payment_cancel');if(!ret&&!cancel)return;history.replaceState(null,'',location.pathname+location.hash);if(!currentUser){page('authPage');return;}await window.openClientView('billing');try{await loadPaymentOrders()}catch(error){toast(error.message)}if(cancel){toast(tr('Payment cancelled. No subscription was activated.','تم إلغاء الدفع دون تفعيل أي اشتراك.'));return}try{const orders=await api('/api/billing/orders');const order=orders.find(o=>o.id===ret);const status=order&&order.status;if(status==='paid')toast(tr('Payment verified. Subscription active.','تم التحقق من الدفع وتفعيل الاشتراك.'));else if(status==='sandbox_paid')toast(tr('Sandbox payment recorded. Real subscription unchanged.','سُجل الدفع التجريبي دون تفعيل اشتراك حقيقي.'));else if(status)toast(tr('Payment is pending verification. Press Confirm PayPal payment in Payment orders.','الدفع بانتظار التحقق. اضغط تأكيد دفع PayPal في طلبات الدفع.'));else toast(tr('Returned from PayPal. Confirm your payment in Payment orders.','عدت من PayPal. أكد الدفع من طلبات الدفع.'))}catch(error){toast(error.message)}}).catch(error=>toast(error.message));
  setInterval(async()=>{if(!currentUser||admin()||!document.querySelector('#workspacePage.active,#workspaceHomePage.active'))return;try{await refreshEntitlement();}catch(error){toast(error.message);}},30000);
  document.addEventListener('click',event=>{if(event.target.closest('#clientNav [data-client-view=billing]'))loadPaymentOrders().catch(e=>toast(e.message));if(event.target.closest('#adminNav [data-admin-view=billing]'))loadPaymentOrders(true).catch(e=>toast(e.message));});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden&&q('workspacePage').classList.contains('active'))refreshChoices();});
  const choicesObserver=new MutationObserver(()=>{if(q('workspacePage').classList.contains('active')&&activeWorkspace)refreshChoices();});choicesObserver.observe(q('workspacePage'),{attributes:true,attributeFilter:['class']});
  matchMedia('(max-width:1100px)').addEventListener('change',()=>{pane.classList.remove('open');overlay(false);});
  applyPrefs();
})();
