/* Owned account management; all durable data goes through the authenticated API. */
(() => {
  const translations=new Map();
  const tr=(en,ar)=>{translations.set(en,[en,ar]);translations.set(ar,[en,ar]);return lang==='ar'?ar:en};
  const node=(tag,text='',cls='')=>{const n=textElement(tag,text,cls);if(translations.has(text)){const [en,ar]=translations.get(text);n.dataset.managementEn=en;n.dataset.managementAr=ar}return n};
  const priorPreferences=applyPrefs;applyPrefs=function(){priorPreferences();$$('[data-management-en]').forEach(n=>{for(const child of n.childNodes)if(child.nodeType===3)child.textContent=lang==='ar'?n.dataset.managementAr:n.dataset.managementEn})};
  const button=(label,run)=>{const b=node('button',label,'button ghost');b.type='button';b.onclick=async()=>{b.disabled=true;try{await run()}catch(e){toast(e.message)}finally{b.disabled=false}};return b};
  const section=(root,title)=>{const s=node('section','','manage-card');s.append(node('h2',title));root.append(s);return s};
  const input=(form,label,name,type='text',value='')=>{const l=node('label',label),i=node('input');i.name=name;i.type=type;i.value=value;l.append(i);form.append(l);return i};
  const select=(form,label,name,options)=>{const l=node('label',label),i=node('select');i.name=name;options.forEach(([v,t])=>i.add(new Option(t,v)));l.append(i);form.append(l);return i};
  const form=(root,fields,label,run)=>{const f=node('form','','manage-form');fields(f);const b=node('button',label,'button');b.type='submit';f.append(b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await run(Object.fromEntries(new FormData(f)),f);if(f.formDialog?.open)f.formDialog.close()}catch(error){let status=f.querySelector('[role=alert]');if(!status){status=node('p');status.setAttribute('role','alert');f.append(status)}status.textContent=error.message;toast(error.message)}finally{b.disabled=false}};root.append(f);window.mountFormDialog(root,f,root.querySelector('h2')?.textContent||label);if(root.closest('.recovery-box'))f.openDialog();return f};
  const row=(root,title,detail,actions=[])=>{const r=node('div','','manage-row'),copy=node('div');copy.append(node('strong',title),node('small',detail));const a=node('div','','manage-actions');a.append(...actions);r.append(copy,a);root.append(r)};
  function signOut(){currentUser=null;activeWorkspace=null;activeSession=null;activeProject=null;stopEvents();updateNavigation();showPage('authPage')}
  const admin=()=>['admin','owner'].includes(currentUser?.role);

  const main=node('main','','page portal-page');main.id='managementPage';protectedPages.add(main.id);
  const header=node('header','','portal-header');header.append(button(tr('← Back','← رجوع'),()=>page(authenticatedHome())),node('strong','OpenCode Gateway'),button(tr('Workspace','مساحة العمل'),()=>page(activeWorkspace?'workspacePage':'onboarding')));
  const body=node('div','','manage-body');main.append(header,body);document.querySelector('#app-main').append(main);
  async function render(root,name,isPlatform=false){
    await authReady;if(!currentUser)return page('authPage');
    if(isPlatform&&!admin())throw new Error('Administrator access required');
    root.replaceChildren();root.dataset.managementSection=name;
    const loader={security,billing,connections,roles,locations,logs,providers,lifecycle}[name];
    if(!loader)throw new Error('Unknown section');
    try{await loader(root,isPlatform)}catch(e){root.append(node('p',e.message))}
  }
  async function open(name='security',isPlatform=false){
    await authReady;if(!currentUser)return page('authPage');
    if(isPlatform&&!admin()){toast('Administrator access required');return}
    if(!admin()&&['connections','providers'].includes(name))return window.openConnections(name==='providers'?'providers':'github');
    const client={security:'security',billing:'billing',connections:'github',providers:'ai',logs:'account',lifecycle:'account'};
    const administration={security:'security',billing:'billing',connections:'github',roles:'users',locations:'settings',logs:'audit'};
    if(isPlatform)return window.openAdminView(administration[name]);
    if(admin()&&['security','logs','lifecycle'].includes(name))return window.openAdminView(name==='security'?'security':'account');
    if(admin()&&name==='providers')return window.openAdminView('policy');
    return window.openClientView(client[name]);
  }
  async function security(body,platform=false){
    const change=section(body,tr('Change password','تغيير كلمة المرور'));
    form(change,f=>{input(f,tr('Current password','كلمة المرور الحالية'),'current_password','password').required=true;const n=input(f,tr('New password: 8+, number and symbol','كلمة جديدة: 8 أحرف، رقم ورمز'),'new_password','password');n.minLength=8;n.required=true},tr('Change and sign out','تغيير وتسجيل الخروج'),async values=>{await api('/api/account/password',{method:'PUT',body:JSON.stringify(values)});signOut()});
    const sessions=section(body,tr('Active sessions','الجلسات النشطة'));
    for(const s of await api('/api/account/sessions'))row(sessions,tr(s.current?'This session':'Other session',s.current?'الجلسة الحالية':'جلسة أخرى'),new Date(s.created_at).toLocaleString(),[button(tr('Sign out','تسجيل الخروج'),async()=>{await api('/api/account/sessions/'+s.id,{method:'DELETE'});if(s.current)signOut();else await open('security')})]);
    const twoFactor=section(body,tr('Two-factor authentication','المصادقة الثنائية'));
    twoFactor.append(node('p',tr('Not available yet. Two-factor authentication is not implemented.','غير متاحة بعد. لم يُنفّذ إعداد المصادقة الثنائية.')));
    const devices=section(body,tr('Devices','الأجهزة'));
    devices.append(node('p',tr('Device identification is not available yet. Use Active sessions above to revoke a sign-in.','معلومات الأجهزة غير متاحة بعد. يمكنك إلغاء تسجيل الدخول من الجلسات النشطة أعلاه.')));
    await logs(body,false,true);
  }
  async function lifecycle(body){
    const close=section(body,tr('Suspend or request deletion','تعليق الحساب أو طلب حذفه'));close.append(node('p',tr('Access stops immediately. Files remain for administrator review. An administrator must reactivate a suspended account.','يتوقف الوصول فورًا، وتبقى الملفات لمراجعة الإدارة. إعادة تنشيط الحساب تتم بواسطة الإدارة.')));
    form(close,f=>{input(f,tr('Your username','اسم المستخدم'),'confirmation').required=true;input(f,tr('Current password','كلمة المرور الحالية'),'password','password').required=true;select(f,tr('Action','الإجراء'),'action',[['suspend',tr('Suspend','تعليق')],['delete',tr('Request deletion','طلب الحذف')]])},tr('Confirm','تأكيد'),async values=>{if(!await window.confirmAction(tr('Disable access to this account?','تعطيل الوصول إلى هذا الحساب؟')))return;await api('/api/account/lifecycle',{method:'POST',body:JSON.stringify(values)});signOut()});
  }
  async function billing(body,platform=false){
    if(!platform){
      body.dataset.billingRole='customer';
      const box=section(body,tr('Accepted payment methods','وسائل الدفع المتاحة'));
      box.append(node('p',tr('Choose a plan above to open checkout. Select a method configured by the platform and complete payment for your account.','اختر خطة من الأعلى لفتح نموذج الدفع، ثم اختر وسيلة أعدّتها المنصة وأكمل الدفع لحسابك.')));
      const methods=await api('/api/billing/available-methods');
      for(const m of methods)row(box,m.label,m.details.checkout_mode==='paypal'?tr('PayPal · verified online payment','PayPal · دفع إلكتروني موثّق'):m.details.checkout_mode==='link'?tr('Hosted checkout · receipt verification required','دفع عبر رابط · يتطلب التحقق من الاستلام'):tr('Bank / wallet transfer · receipt verification required','تحويل بنكي / محفظة · يتطلب التحقق من الاستلام'));
      if(!methods.length)box.append(node('p',tr('Administration has not configured a payment method yet.','لم تُعدّ الإدارة وسيلة دفع بعد.')));
      return;
    }
    if(!admin())throw new Error('Administrator access required');
    body.dataset.billingRole='admin';
    const box=section(body,tr('Platform receiving methods','وسائل استلام المنصة'));
    box.append(node('p',tr('Configure where the platform receives payments. Customers choose these methods at checkout; they cannot edit them. These methods use manual receipt verification. Google Pay needs a processor-hosted checkout link; Binance transfers require receipt review. Do not enter card numbers, CVV or private keys.','أعدّ وسائل استلام مدفوعات المنصة. يختارها العميل أثناء الدفع ولا يستطيع تعديلها. هذه الوسائل تتطلب التحقق اليدوي من الاستلام. لا تدخل أرقام بطاقات أو CVV أو مفاتيح خاصة.')));
    const paymentStatus=await api('/api/billing/paypal/status');box.append(node('p',tr('PayPal API: '+(paymentStatus.configured?'configured':'merchant setup required')+' · '+paymentStatus.environment,'PayPal API: '+(paymentStatus.configured?'مهيأ':'يتطلب إعداد التاجر')+' · '+paymentStatus.environment)));const query=platform?'?platform=true':'',items=await api('/api/billing/methods'+query),plans=await api('/api/plans');let editing=null;
    const editor=section(body,tr('Add or edit method','إضافة وسيلة أو تعديلها'));
    const f=form(editor,f=>{select(f,tr('Type','النوع'),'kind',[['paypal','PayPal'],['googlepay','Google Pay'],['binance','Binance'],['bank',tr('Bank account','حساب بنكي')],['wallet',tr('Wallet','محفظة')],['other',tr('Other','أخرى')]]);input(f,tr('Label','الاسم'),'label').required=true;select(f,tr('Checkout','طريقة الدفع'),'checkout_mode',[['manual',tr('Bank / wallet transfer','تحويل بنكي / محفظة')],['link',tr('Hosted payment link / PayPal','رابط دفع / PayPal')],['paypal',tr('PayPal API — verified payment','PayPal API — دفع موثّق')]]);input(f,tr('Payment link (HTTPS)','رابط الدفع (HTTPS)'),'payment_url','url');select(f,tr('Plan for this link','الخطة الخاصة بالرابط'),'plan_id',[['',tr('All plans (transfers only)','كل الخطط (التحويل فقط)')],...plans.filter(p=>p.active!==false).map(p=>[String(p.id),p.name+' · '+p.currency+' '+(p.price_cents/100).toFixed(2)])]);select(f,tr('Bank shortcut','اختيار البنك'),'bank_shortcut',[['','—'],['Al-Qutaibi','القطيبي · Al-Qutaibi'],['Al-Kuraimi','الكريمي · Al-Kuraimi']]);for(const [n,en,ar] of [['account_name','Account holder','صاحب الحساب'],['account_reference','Email / IBAN / wallet address','البريد / IBAN / عنوان المحفظة'],['bank_name','Bank name','اسم البنك'],['currency','Currency','العملة'],['network','Wallet network','شبكة المحفظة'],['instructions','Instructions','التعليمات']])input(f,tr(en,ar),n,'text',n==='currency'?'USD':'');select(f,tr('Status','الحالة'),'enabled',[['true',tr('Enabled','مفعّل')],['false',tr('Disabled','معطّل')]])},tr('Save method','حفظ الوسيلة'),async values=>{values.enabled=values.enabled==='true';values.plan_id=values.plan_id?Number(values.plan_id):null;delete values.bank_shortcut;if(values.kind!=='bank')values.bank_name='';if(!['wallet','binance'].includes(values.kind))values.network='';if(values.checkout_mode!=='link')values.payment_url='';await api('/api/billing/methods'+(editing?'/'+editing:'')+query,{method:editing?'PUT':'POST',body:JSON.stringify(values)});await open('billing',platform)});
    f.dataset.paymentForm='platform';
    const guidance=node('p','','payment-setup-guidance');guidance.setAttribute('role','note');f.prepend(guidance);
    const examples={label:['Example: Al-Qutaibi bank transfer','مثال: تحويل بنك القطيبي'],account_name:['Example: your legal account name','مثال: اسمك المسجل في الحساب'],account_reference:['Example: receiving email, account number or Binance UID','مثال: بريد الاستلام أو رقم الحساب أو معرّف Binance'],payment_url:['https://checkout.your-provider.example/plan-monthly','https://checkout.your-provider.example/plan-monthly'],bank_name:['Example: Al-Qutaibi / Al-Kuraimi','مثال: القطيبي / الكريمي'],network:['Example: Binance internal transfer / agreed token network','مثال: تحويل Binance الداخلي / شبكة العملة المتفق عليها'],instructions:['Explain how to pay, currency, and receipt reference. Examples are not real receiving details.','وضح طريقة الدفع والعملة ومرجع الإيصال. الأمثلة ليست بيانات استلام حقيقية.']};
    for(const [name,[en,ar]] of Object.entries(examples))f.elements[name].placeholder=tr(en,ar);
    function paymentGuidance(){const kind=f.elements.kind.value,mode=f.elements.checkout_mode.value;const copy=kind==='googlepay'?['Create a checkout link with a payment processor that supports Google Pay. Paste its HTTPS URL and select the matching plan/currency. Enable only after testing.','أنشئ رابط دفع لدى مزود يدعم Google Pay. أدخل رابط HTTPS وحدد الخطة والعملة المطابقتين. فعّله بعد الاختبار فقط.']:mode==='paypal'?['Backend setup required: PAYPAL_CLIENT_ID, PAYPAL_CLIENT_SECRET, PAYPAL_MERCHANT_ID, PAYPAL_ENVIRONMENT=sandbox, PUBLIC_BASE_URL. Put values in the private backend environment and restart. Use PAYPAL_SANDBOX_DECLINE=true for a sandbox-issued decline test; never in live. Email alone does not connect the merchant API.','يلزم إعداد الخلفية: PAYPAL_CLIENT_ID وPAYPAL_CLIENT_SECRET وPAYPAL_MERCHANT_ID وPAYPAL_ENVIRONMENT=sandbox وPUBLIC_BASE_URL. ضع القيم في بيئة الخلفية الخاصة وأعد التشغيل. لاختبار رفض تجريبي استخدم PAYPAL_SANDBOX_DECLINE=true في Sandbox فقط. البريد وحده لا يربط واجهة التاجر.']:mode==='link'?['Create a real payment link in your merchant service. Match its price and currency to the selected plan. The client pays on that service, then submits a receipt. Administration verifies payment before activation.','أنشئ رابط دفع حقيقي من خدمة التاجر. طابق السعر والعملة مع الخطة المختارة. يدفع العميل في صفحة الخدمة ثم يرسل مرجع الإيصال، وتتحقق الإدارة قبل التفعيل.']:kind==='binance'?['Enter your confirmed Binance receiving email or UID. State the accepted asset/network and exact amount in instructions. Check the actual transaction in Binance before confirming a receipt. This is a manual transfer, not Binance Pay API.','أدخل بريد استلام Binance أو UID الموثق. وضح العملة والشبكة والمبلغ في التعليمات. تحقق من العملية داخل Binance قبل تأكيد الإيصال. هذا تحويل يدوي وليس ربط Binance Pay API.']:['Enter the real recipient name, account number/address, currency and transfer instructions. Customers submit references; administration checks the actual receipt. Never enter card details or private keys.','أدخل اسم المستفيد ورقم الحساب أو العنوان والعملة وتعليمات التحويل الحقيقية. يرسل العميل مرجع العملية وتتحقق الإدارة من الاستلام. لا تدخل بيانات بطاقات أو مفاتيح خاصة.'];guidance.textContent=tr(...copy);}

    function methodFields(){const kind=f.elements.kind.value;for(const name of ['bank_name','network'])f.elements[name].parentElement.hidden=name==='bank_name'?kind!=='bank':!['wallet','binance'].includes(kind);}
    const originalMethodFields=methodFields;methodFields=function(){originalMethodFields();const linked=f.elements.checkout_mode.value==='link';for(const name of ['payment_url','plan_id']){f.elements[name].parentElement.hidden=!linked;f.elements[name].required=linked&&f.elements.enabled.value==='true';}f.elements.bank_shortcut.parentElement.hidden=f.elements.kind.value!=='bank';paymentGuidance();};f.elements.enabled.onchange=methodFields;f.elements.checkout_mode.onchange=methodFields;f.elements.bank_shortcut.onchange=()=>{if(f.elements.bank_shortcut.value){f.elements.bank_name.value=f.elements.bank_shortcut.value;f.elements.label.value=f.elements.bank_shortcut.value;}};f.elements.kind.onchange=()=>{if(f.elements.kind.value==='googlepay')f.elements.checkout_mode.value='link';methodFields();};methodFields();
    editor.append(button(tr('New method','وسيلة جديدة'),()=>{editing=null;f.reset();methodFields();f.openDialog()}));
    const presets=node('div','','manage-actions');editor.append(node('p',tr('Start with an example below. Examples are disabled drafts: replace every example value and configure the provider before enabling.','ابدأ بأحد الأمثلة أدناه. الأمثلة مسودات معطّلة: استبدل القيم وأكمل إعداد المزود قبل التفعيل.')),presets);
    for(const [label,kind,mode,bank] of [['PayPal','paypal','paypal',''],['Google Pay','googlepay','link',''],['Binance','binance','manual',''],['Al-Qutaibi','bank','manual','Al-Qutaibi'],['Al-Kuraimi','bank','manual','Al-Kuraimi']])presets.append(button(tr('Example: '+label,'مثال: '+label),()=>{editing=null;f.reset();const draft={kind,label,checkout_mode:mode,enabled:'false',currency:'USD',bank_name:bank,account_name:'EXAMPLE_REPLACE_ACCOUNT_NAME',account_reference:kind==='googlepay'?'':'EXAMPLE_REPLACE_RECEIVING_ACCOUNT',network:kind==='binance'?'EXAMPLE_REPLACE_ASSET_AND_NETWORK':'',payment_url:mode==='link'?'https://checkout.example.com/your-plan':'',plan_id:'',instructions:tr('EXAMPLE: replace receiver details, specify the accepted currency/asset and exact amount; verify receipt before activation.','مثال: استبدل بيانات المستفيد وحدد العملة والمبلغ، وتحقق من الاستلام قبل التفعيل.')};for(const [name,value] of Object.entries(draft))f.elements[name].value=value;methodFields();f.openDialog();}));

    for(const m of items)row(box,m.label,m.kind+' · '+(m.enabled?tr('Enabled','مفعّل'):tr('Disabled','معطّل')),[button(tr('Edit','تعديل'),()=>{editing=m.id;f.reset();for(const [k,v] of Object.entries({...m.details,kind:m.kind,label:m.label,enabled:String(m.enabled)}))if(f.elements.namedItem(k))f.elements.namedItem(k).value=v;methodFields();f.openDialog()}),button(tr('Delete','حذف'),async()=>{if(!await window.confirmAction(tr('Delete saved method?','حذف الوسيلة المحفوظة؟')))return;await api('/api/billing/methods/'+m.id+query,{method:'DELETE'});await open('billing',platform)})]);
    if(!items.length)box.append(node('p',tr('No saved methods','لا توجد وسائل محفوظة')));
    if(!platform){const receiving=section(body,tr('Platform receiving methods','وسائل الاستلام في المنصة'));for(const m of await api('/api/billing/available-methods'))row(receiving,m.label,Object.values(m.details).filter(Boolean).join(' · '))}
  }
  async function connections(body,platform=false){const box=section(body,tr('GitHub connections','اتصالات GitHub'));if(platform){for(const c of await api('/api/admin/connections'))row(box,c.login,c.user_id,[button(tr('Disconnect','إلغاء الربط'),async()=>{if(!await window.confirmAction('Disconnect this account?'))return;await api('/api/admin/connections/'+c.user_id,{method:'DELETE'});await open('connections',true)})]);return}
    const status=await api('/api/github/status');row(box,status.account_login||tr('Not connected','غير متصل'),status.configured?tr('GitHub App configured','تطبيق GitHub مهيأ'):tr('Administrator must configure the GitHub App','يجب على الإدارة إعداد تطبيق GitHub'));
    const authorize=button(tr('Authorize GitHub','تفويض GitHub'),()=>{window.location.assign('/api/github/install')});authorize.disabled=!status.configured;box.append(authorize);
    for(const [en,ar] of [['Repositories','المستودعات'],['Branches','الفروع']]){const s=section(body,tr(en,ar));if(!status.connected)s.append(node('p',tr('Connect and authorize GitHub to access your repositories and branches.','اربط GitHub وفوّضه للوصول إلى مستودعاتك وفروعها.')));}
    if(status.connected){box.append(button(tr('Disconnect GitHub','إلغاء ربط GitHub'),async()=>{await api('/api/github/disconnect',{method:'POST'});await open('connections')}));
      const repos=await api('/api/github/repositories');let repository,branch;
      form(box,f=>{repository=select(f,tr('Repository','المستودع'),'repository',[['',tr('Choose repository','اختر مستودعًا')],...repos.map(r=>[r.full_name,r.full_name])]);repository.required=true;branch=select(f,tr('Branch','الفرع'),'branch',[]);branch.required=true;input(f,tr('Project name','اسم المشروع'),'project_name').required=true;repository.onchange=async()=>{branch.replaceChildren();if(!repository.value)return;try{for(const b of await api('/api/github/branches?repository='+encodeURIComponent(repository.value)))branch.add(new Option(b.name,b.name))}catch(e){toast(e.message)}}},tr('Create workspace','إنشاء مساحة عمل'),async values=>{const result=await api('/api/projects',{method:'POST',body:JSON.stringify({...values,source_type:'github'})});await openWorkspace(result.project,result.workspace)});
    }
  }
  async function providers(body,platform=false){const workspaceSettings=section(body,tr('Runtime / workspace settings','إعدادات وقت التشغيل ومساحة العمل'));
    const [workspaces,projects]=await Promise.all([api('/api/workspaces'),api('/api/projects')]);const picker=select(workspaceSettings,tr('Workspace','مساحة العمل'),'workspace',[['',tr('Select workspace','اختر مساحة عمل')],...workspaces.map(w=>[w.id,(projects.find(p=>p.id===w.project_id)?.name||tr('Workspace','مساحة عمل'))+' · '+w.status])]);picker.value=activeWorkspace?.id||'';
    picker.onchange=async()=>{const w=workspaces.find(w=>w.id===picker.value);if(!w)return;try{await openWorkspace(await api('/api/projects/'+w.project_id),w);await open('providers')}catch(e){toast(e.message)}};
    const model=section(body,tr('Model','النموذج'));model.append(node('p',tr('Choose a connected provider and model in the workspace composer. Model selection applies to the conversation.','اختر المزود المتصل والنموذج من محرر الدردشة داخل مساحة العمل. اختيار النموذج يخص المحادثة.')));
    const credentialsPanel=section(body,tr('Provider credentials','بيانات اتصال المزود'));credentialsPanel.append(node('p',tr('Encrypted API keys and provider authorization belong to the selected workspace.','مفاتيح API المشفرة وتفويض المزود يخصّان مساحة العمل المحددة.')));
    const box=section(body,tr('Workspace providers','مزودو مساحة العمل'));box.append(node('p',tr('Credentials belong to the selected workspace. Saving a key does not verify a paid model request. OAuth credentials are managed by OpenCode; database backup of OAuth tokens is not supported yet.','بيانات الاتصال تخص مساحة العمل المحددة. حفظ المفتاح لا يتحقق من نجاح طلب النموذج. يدير OpenCode بيانات OAuth، ولم تُضف بعد نسختها الاحتياطية إلى قاعدة البيانات.')));box.append(button(tr('Open workspace','فتح مساحة العمل'),()=>activeWorkspace?page('workspacePage'):window.openClientView('projects')));if(!activeWorkspace)return;
    const workspaceId=activeWorkspace.id,base='/api/workspaces/'+workspaceId+'/providers/';const available=await api('/api/workspaces/'+workspaceId+'/providers');
    for(const provider of available){const panel=section(body,provider.name);panel.append(node('p',provider.connected?tr('Configured in runtime','مهيأ في الخدمة'):tr('Not connected','غير متصل')));
      if(!provider.auth_methods.length||provider.auth_methods.some(m=>m.type==='api'))form(panel,f=>{input(f,tr('API key','مفتاح API'),'api_key','password').required=true},tr('Save encrypted key','حفظ المفتاح مشفرًا'),async(values,f)=>{await api(base+encodeURIComponent(provider.id)+'/credentials',{method:'POST',body:JSON.stringify(values)});f.reset();await open('providers')});
      provider.auth_methods.forEach((method,index)=>{if(method.type!=='oauth')return;panel.append(button(method.label||'OAuth',async()=>{const result=await api(base+encodeURIComponent(provider.id)+'/oauth/authorize',{method:'POST',body:JSON.stringify({method:index})});const destination=new URL(result.url);if(destination.protocol!=='https:')throw new Error('Provider returned an unsupported authorization URL');const link=node('a',tr('Open provider authorization','فتح تفويض المزود'),'button');link.href=destination.href;link.target='_blank';link.rel='noopener noreferrer';panel.append(link,node('p',result.instructions||''));form(panel,f=>{if(result.method==='code')input(f,tr('Authorization code','رمز التفويض'),'code').required=true},tr('Complete authorization','إكمال التفويض'),async values=>{await api(base+encodeURIComponent(provider.id)+'/oauth/callback',{method:'POST',body:JSON.stringify({method:index,...values})});await open('providers')})}))});
      if(provider.connected)panel.append(button(tr('Disconnect provider','إلغاء ربط المزود'),async()=>{await api(base+encodeURIComponent(provider.id),{method:'DELETE'});await open('providers')}));
    }
  }
  async function roles(body,platform=false){const box=section(body,tr('User roles','أدوار المستخدمين'));for(const u of await api('/api/admin/users'))row(box,u.username,u.role,[...(currentUser.role==='owner'&&u.id!==currentUser.id&&u.role!=='owner'?[button(tr('Change role','تغيير الدور'),async()=>{const picked=await window.requestForm(tr('Change role','تغيير الدور'),[{name:'role',label:tr('Role','الدور'),value:u.role,options:['admin','support','finance','customer']}]);const role=picked?.role;if(!role)return;await api('/api/admin/users/'+u.id+'/role',{method:'PUT',body:JSON.stringify({role})});await open('roles',true)})]:[])]);box.append(node('p',tr('Only an owner can assign roles. Finance can manage platform payment methods through its authorized API. Support currently has account-only access.','المالك وحده يعيّن الأدوار. دور المالية يتيح إدارة وسائل المنصة عبر واجهته المصرح بها. الدعم يمتلك حاليًا صلاحيات الحساب الشخصي فقط.')))}
  async function logs(body,platform=false,securityOnly=false){const box=section(body,tr(platform?'Audit log':securityOnly?'Login / security activity':'Account activity',platform?'سجل الإجراءات':securityOnly?'نشاط الدخول والأمان':'نشاط الحساب'));if(securityOnly)box.append(node('p',tr('Recorded password and session security actions. Login event tracking is not available yet.','إجراءات كلمة المرور والجلسات المسجلة. تتبع أحداث تسجيل الدخول غير متاح بعد.')));let before;async function load(){const items=await api((platform?'/api/admin/logs':'/api/account/logs')+(before?'?before='+before:''));for(const r of items.filter(r=>platform||(/^(password|session|auth|security|role)\./.test(r.action)===securityOnly)))row(box,r.action,new Date(r.created_at).toLocaleString());before=items.at(-1)?.id;more.hidden=items.length<100}const more=button(tr('Older records','سجلات أقدم'),load);body.append(more);await load()}
  async function locations(body,platform=false){const box=section(body,tr('Locations','المواقع'));let kind='countries',editing=null;const picker=select(box,tr('Type','النوع'),'type',[['countries',tr('Countries','الدول')],['regions',tr('Regions','المناطق')],['cities',tr('Cities','المدن')]]),list=node('div');box.append(list);const editor=section(body,tr('Location details','بيانات الموقع'));let parent;
    const f=form(editor,f=>{input(f,tr('Name','الاسم'),'name').required=true;input(f,tr('Country code','رمز الدولة'),'code');parent=select(f,tr('Parent location','الموقع الأب'),'parent_id',[]);select(f,tr('Enabled','مفعّل'),'enabled',[['true',tr('Yes','نعم')],['false',tr('No','لا')]])},tr('Save','حفظ'),async values=>{values.enabled=values.enabled==='true';values.parent_id=values.parent_id?Number(values.parent_id):null;values.code=values.code||null;await api('/api/admin/locations/'+kind+(editing?'/'+editing:''),{method:editing?'PUT':'POST',body:JSON.stringify(values)});await refresh()});
    async function refresh(){editing=null;f.reset();list.replaceChildren();parent.replaceChildren(new Option('—',''));if(kind!=='countries')for(const p of await api('/api/admin/locations/'+(kind==='regions'?'countries':'regions')))parent.add(new Option(p.name,p.id));for(const r of await api('/api/admin/locations/'+kind))row(list,r.name,r.enabled?tr('Enabled','مفعّل'):tr('Disabled','معطّل'),[button(tr('Edit','تعديل'),()=>{editing=r.id;for(const [k,v] of Object.entries({...r,parent_id:r.country_id||r.region_id||'',enabled:String(r.enabled)}))if(f.elements.namedItem(k))f.elements.namedItem(k).value=v;f.openDialog()}),button(tr('Disable','تعطيل'),async()=>{await api('/api/admin/locations/'+kind+'/'+r.id,{method:'DELETE'});await refresh()})])}
    picker.onchange=()=>{kind=picker.value;refresh().catch(e=>toast(e.message))};await refresh();
  }
  const github=$('#chatGithub');if(github)github.onclick=()=>open('connections');
  const oldRefreshGit=refreshGit;refreshGit=async function(){await oldRefreshGit();const b=$('#manageProviders');if(b)b.onclick=()=>open('providers')};
  const welcome=$('#welcomePrompt');const connect=button(tr('Connect GitHub · choose repository & branch','اربط GitHub · اختر المستودع والفرع'),()=>open('connections'));connect.classList.add('landing-connect');const logo=document.createElementNS('http://www.w3.org/2000/svg','svg');const use=document.createElementNS('http://www.w3.org/2000/svg','use');use.setAttribute('href','#icon-github');logo.append(use);connect.prepend(logo);welcome.after(connect);
  const tools=node('div','','manage-actions workspace-links');tools.append(button(tr('Switch workspace','تبديل مساحة العمل'),()=>window.openClientView('projects')),button(tr('Another repository','مستودع آخر'),()=>page('onboarding')));$('#promptForm').before(tools);
  const recovery=node('section','','manage-card recovery-box');recovery.hidden=true;$('#authPage').append(recovery);let resetToken=new URLSearchParams(location.hash.slice(1)).get('reset-password');if(resetToken)history.replaceState(null,'',location.pathname+location.search);
  function closeRecovery(){window.passwordRecoveryActive=false;recovery.hidden=true;$('#authPage .auth-shell').hidden=false;window.scrollTo(0,0)}
  function recover(reset=false){window.passwordRecoveryActive=true;document.getElementById('authDialog')?.close();showPage('authPage');$('#authPage .auth-shell').hidden=true;recovery.hidden=false;recovery.replaceChildren(node('h2',tr(reset?'Reset password':'Recover password',reset?'إعادة تعيين كلمة المرور':'استعادة كلمة المرور')));form(recovery,f=>{const i=input(f,tr(reset?'New password: 8+, number and symbol':'Account email',reset?'كلمة جديدة: 8 أحرف ورقم ورمز':'بريد الحساب'),reset?'password':'email',reset?'password':'email');i.required=true;if(reset)i.minLength=8},tr(reset?'Reset':'Send recovery link',reset?'إعادة تعيين':'إرسال رابط الاستعادة'),async values=>{const data=await api(reset?'/api/auth/reset-password':'/api/auth/forgot-password',{method:'POST',body:JSON.stringify(reset?{token:resetToken,password:values.password}:values)});toast(data.message);if(reset){resetToken=null;closeRecovery();signOut()}});recovery.append(button(tr('Back to login','رجوع للدخول'),closeRecovery));window.scrollTo(0,0)}
  const forgot=$('#authPage .auth-form .text-link');if(forgot){forgot.disabled=false;forgot.textContent=tr('Forgot password?','نسيت كلمة المرور؟');forgot.onclick=()=>recover()}
  window.renderManagement=render;
  window.openManagement=open;
  if(resetToken)recover(true);
})();
