/* Owned account management; all durable data goes through the authenticated API. */
(() => {
  const translations=new Map();
  const tr=(en,ar)=>{translations.set(en,[en,ar]);translations.set(ar,[en,ar]);return lang==='ar'?ar:en};
  const node=(tag,text='',cls='')=>{const n=textElement(tag,text,cls);if(translations.has(text)){const [en,ar]=translations.get(text);n.dataset.managementEn=en;n.dataset.managementAr=ar}return n};
  const priorPreferences=applyPrefs;applyPrefs=function(){priorPreferences();$$('[data-management-en]').forEach(n=>{for(const child of n.childNodes)if(child.nodeType===3)child.textContent=lang==='ar'?n.dataset.managementAr:n.dataset.managementEn})};
  const button=(label,run)=>{const b=node('button',label,'button ghost');b.type='button';b.onclick=async()=>{b.disabled=true;try{await run()}catch(e){toast(e.message)}finally{b.disabled=false}};return b};
  const section=(root,title)=>{const s=node('section','','manage-card');s.append(node('h2',title));root.append(s);return s};
  const input=(form,label,name,type='text',value='')=>{const l=node('label',label),i=node('input');i.name=name;i.type=type;i.value=value;l.append(i);form.append(l);return i};
  const select=(form,label,name,options)=>{const l=node('label',label),i=node('select');i.name=name;options.forEach(([v,t])=>i.add(new Option(t,v)));l.append(i);form.append(l);return i};
  const form=(root,fields,label,run)=>{const f=node('form','','manage-form');fields(f);const b=node('button',label,'button');b.type='submit';f.append(b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await run(Object.fromEntries(new FormData(f)),f)}catch(error){toast(error.message)}finally{b.disabled=false}};root.append(f);return f};
  const row=(root,title,detail,actions=[])=>{const r=node('div','','manage-row'),copy=node('div');copy.append(node('strong',title),node('small',detail));const a=node('div','','manage-actions');a.append(...actions);r.append(copy,a);root.append(r)};
  function signOut(){currentUser=null;activeWorkspace=null;activeSession=null;activeProject=null;stopEvents();updateNavigation();showPage('authPage')}
  const admin=()=>['admin','owner'].includes(currentUser?.role);
  let tab='security',platform=false;
  const main=node('main','','page portal-page');main.id='managementPage';protectedPages.add(main.id);
  const header=node('header','','portal-header');header.append(button(tr('← Back','← رجوع'),()=>page(platform?'adminPage':'accountPage')),node('strong','OpenCode Gateway'),button(tr('Workspace','مساحة العمل'),()=>page(activeWorkspace?'workspacePage':'onboarding')));
  const layout=node('div','','manage-layout'),nav=node('nav','','manage-nav'),body=node('div','','manage-body');layout.append(nav,body);main.append(header,layout);document.body.insertBefore(main,$('#toast'));
  async function open(name='security',isPlatform=false){await authReady;if(!currentUser)return page('authPage');if(isPlatform&&!admin()){toast('Administrator access required');return}tab=name;platform=isPlatform;showPage('managementPage');nav.replaceChildren();for(const [id,en,ar] of (platform?[['billing','Payment methods','وسائل الدفع'],['connections','Connections','الاتصالات'],['roles','Roles','الأدوار'],['locations','Locations','المواقع'],['logs','Audit logs','سجل الإجراءات']]:[['security','Security','الأمان'],['billing','Billing','الفوترة'],['connections','GitHub & repositories','GitHub والمستودعات'],['providers','AI providers','مزودو الذكاء'],['logs','Activity','النشاط']])){const b=button(tr(en,ar),()=>open(id,platform));b.classList.toggle('active',id===name);nav.append(b)}body.replaceChildren();try{await ({security,billing,connections,roles,locations,logs,providers}[name])()}catch(e){body.append(node('p',e.message))}}
  async function security(){
    const change=section(body,tr('Change password','تغيير كلمة المرور'));
    form(change,f=>{input(f,tr('Current password','كلمة المرور الحالية'),'current_password','password').required=true;const n=input(f,tr('New password: 8+, number and symbol','كلمة جديدة: 8 أحرف، رقم ورمز'),'new_password','password');n.minLength=8;n.required=true},tr('Change and sign out','تغيير وتسجيل الخروج'),async values=>{await api('/api/account/password',{method:'PUT',body:JSON.stringify(values)});signOut()});
    const sessions=section(body,tr('Active sign-ins','جلسات تسجيل الدخول'));
    for(const s of await api('/api/account/sessions'))row(sessions,tr(s.current?'This session':'Other session',s.current?'الجلسة الحالية':'جلسة أخرى'),new Date(s.created_at).toLocaleString(),[button(tr('Sign out','تسجيل الخروج'),async()=>{await api('/api/account/sessions/'+s.id,{method:'DELETE'});if(s.current)signOut();else await open('security')})]);
    const close=section(body,tr('Suspend or request deletion','تعليق الحساب أو طلب حذفه'));close.append(node('p',tr('Access stops immediately. Files remain for administrator review. An administrator must reactivate a suspended account.','يتوقف الوصول فورًا، وتبقى الملفات لمراجعة الإدارة. إعادة تنشيط الحساب تتم بواسطة الإدارة.')));
    form(close,f=>{input(f,tr('Your username','اسم المستخدم'),'confirmation').required=true;input(f,tr('Current password','كلمة المرور الحالية'),'password','password').required=true;select(f,tr('Action','الإجراء'),'action',[['suspend',tr('Suspend','تعليق')],['delete',tr('Request deletion','طلب الحذف')]])},tr('Confirm','تأكيد'),async values=>{if(!confirm(tr('Disable access to this account?','تعطيل الوصول إلى هذا الحساب؟')))return;await api('/api/account/lifecycle',{method:'POST',body:JSON.stringify(values)});signOut()});
  }
  async function billing(){
    const box=section(body,tr(platform?'Platform payment methods':'Your payment methods',platform?'وسائل الدفع في المنصة':'وسائل الدفع الخاصة بك'));
    box.append(node('p',tr('These are saved account details, not automatic payments. Do not enter card numbers, CVV, passwords or wallet private keys. Platform methods are visible to customers.','هذه بيانات حساب محفوظة، ولا يتم تحصيل أموال تلقائيًا. لا تدخل أرقام بطاقات أو CVV أو كلمات مرور أو مفاتيح محافظ خاصة. وسائل المنصة تظهر للعملاء.')));
    const query=platform?'?platform=true':'',items=await api('/api/billing/methods'+query);let editing=null;
    const editor=section(body,tr('Add or edit method','إضافة وسيلة أو تعديلها'));
    const f=form(editor,f=>{select(f,tr('Type','النوع'),'kind',[['paypal','PayPal'],['bank',tr('Bank account','حساب بنكي')],['wallet',tr('Wallet','محفظة')],['other',tr('Other','أخرى')]]);input(f,tr('Label','الاسم'),'label').required=true;for(const [n,en,ar] of [['account_name','Account holder','صاحب الحساب'],['account_reference','Email / IBAN / wallet address','البريد / IBAN / عنوان المحفظة'],['bank_name','Bank name','اسم البنك'],['currency','Currency','العملة'],['network','Wallet network','شبكة المحفظة'],['instructions','Instructions','التعليمات']])input(f,tr(en,ar),n,'text',n==='currency'?'USD':'');select(f,tr('Status','الحالة'),'enabled',[['true',tr('Enabled','مفعّل')],['false',tr('Disabled','معطّل')]])},tr('Save method','حفظ الوسيلة'),async values=>{values.enabled=values.enabled==='true';await api('/api/billing/methods'+(editing?'/'+editing:'')+query,{method:editing?'PUT':'POST',body:JSON.stringify(values)});await open('billing',platform)});
    editor.append(button(tr('New method','وسيلة جديدة'),()=>{editing=null;f.reset()}));
    for(const m of items)row(box,m.label,m.kind+' · '+(m.enabled?tr('Enabled','مفعّل'):tr('Disabled','معطّل')),[button(tr('Edit','تعديل'),()=>{editing=m.id;for(const [k,v] of Object.entries({...m.details,kind:m.kind,label:m.label,enabled:String(m.enabled)}))if(f.elements.namedItem(k))f.elements.namedItem(k).value=v;editor.scrollIntoView()}),button(tr('Delete','حذف'),async()=>{if(!confirm(tr('Delete saved method?','حذف الوسيلة المحفوظة؟')))return;await api('/api/billing/methods/'+m.id+query,{method:'DELETE'});await open('billing',platform)})]);
    if(!items.length)box.append(node('p',tr('No saved methods','لا توجد وسائل محفوظة')));
    if(!platform){const receiving=section(body,tr('Platform receiving methods','وسائل الاستلام في المنصة'));for(const m of await api('/api/billing/available-methods'))row(receiving,m.label,Object.values(m.details).filter(Boolean).join(' · '))}
  }
  async function connections(){const box=section(body,tr('GitHub connections','اتصالات GitHub'));if(platform){for(const c of await api('/api/admin/connections'))row(box,c.login,c.user_id,[button(tr('Disconnect','إلغاء الربط'),async()=>{if(!confirm('Disconnect this account?'))return;await api('/api/admin/connections/'+c.user_id,{method:'DELETE'});await open('connections',true)})]);return}
    const status=await api('/api/github/status');row(box,status.account_login||tr('Not connected','غير متصل'),status.configured?tr('GitHub App configured','تطبيق GitHub مهيأ'):tr('Administrator must configure the GitHub App','يجب على الإدارة إعداد تطبيق GitHub'));
    box.append(button(tr('Connect GitHub','ربط GitHub'),()=>{window.location.assign('/api/github/install')}),button(tr('Choose repository and branch','اختيار المستودع والفرع'),()=>page('onboarding')));
    if(status.connected){box.append(button(tr('Disconnect GitHub','إلغاء ربط GitHub'),async()=>{await api('/api/github/disconnect',{method:'POST'});await open('connections')}));
      const repos=await api('/api/github/repositories');let repository,branch;
      form(box,f=>{repository=select(f,tr('Repository','المستودع'),'repository',[['',tr('Choose repository','اختر مستودعًا')],...repos.map(r=>[r.full_name,r.full_name])]);repository.required=true;branch=select(f,tr('Branch','الفرع'),'branch',[]);branch.required=true;input(f,tr('Project name','اسم المشروع'),'project_name').required=true;repository.onchange=async()=>{branch.replaceChildren();if(!repository.value)return;try{for(const b of await api('/api/github/branches?repository='+encodeURIComponent(repository.value)))branch.add(new Option(b.name,b.name))}catch(e){toast(e.message)}}},tr('Create workspace','إنشاء مساحة عمل'),async values=>{const result=await api('/api/projects',{method:'POST',body:JSON.stringify({...values,source_type:'github'})});await openWorkspace(result.project,result.workspace)});
    }
  }
  async function providers(){const box=section(body,tr('Workspace providers','مزودو مساحة العمل'));box.append(node('p',tr('Credentials belong to the selected workspace. Saving a key does not verify a paid model request. OAuth credentials are managed by OpenCode; database backup of OAuth tokens is not supported yet.','بيانات الاتصال تخص مساحة العمل المحددة. حفظ المفتاح لا يتحقق من نجاح طلب النموذج. يدير OpenCode بيانات OAuth، ولم تُضف بعد نسختها الاحتياطية إلى قاعدة البيانات.')));box.append(button(tr('Open workspace','فتح مساحة العمل'),()=>page(activeWorkspace?'workspacePage':'accountPage')));if(!activeWorkspace)return;
    const workspaceId=activeWorkspace.id,base='/api/workspaces/'+workspaceId+'/providers/';const available=await api('/api/workspaces/'+workspaceId+'/providers');
    for(const provider of available){const panel=section(body,provider.name);panel.append(node('p',provider.connected?tr('Configured in runtime','مهيأ في الخدمة'):tr('Not connected','غير متصل')));
      if(!provider.auth_methods.length||provider.auth_methods.some(m=>m.type==='api'))form(panel,f=>{input(f,tr('API key','مفتاح API'),'api_key','password').required=true},tr('Save encrypted key','حفظ المفتاح مشفرًا'),async(values,f)=>{await api(base+encodeURIComponent(provider.id)+'/credentials',{method:'POST',body:JSON.stringify(values)});f.reset();await open('providers')});
      provider.auth_methods.forEach((method,index)=>{if(method.type!=='oauth')return;panel.append(button(method.label||'OAuth',async()=>{const result=await api(base+encodeURIComponent(provider.id)+'/oauth/authorize',{method:'POST',body:JSON.stringify({method:index})});const destination=new URL(result.url);if(destination.protocol!=='https:')throw new Error('Provider returned an unsupported authorization URL');const link=node('a',tr('Open provider authorization','فتح تفويض المزود'),'button');link.href=destination.href;link.target='_blank';link.rel='noopener noreferrer';panel.append(link,node('p',result.instructions||''));form(panel,f=>{if(result.method==='code')input(f,tr('Authorization code','رمز التفويض'),'code').required=true},tr('Complete authorization','إكمال التفويض'),async values=>{await api(base+encodeURIComponent(provider.id)+'/oauth/callback',{method:'POST',body:JSON.stringify({method:index,...values})});await open('providers')})}))});
      if(provider.connected)panel.append(button(tr('Disconnect provider','إلغاء ربط المزود'),async()=>{await api(base+encodeURIComponent(provider.id),{method:'DELETE'});await open('providers')}));
    }
  }
  async function roles(){const box=section(body,tr('User roles','أدوار المستخدمين'));for(const u of await api('/api/admin/users'))row(box,u.username,u.role,[...(currentUser.role==='owner'&&u.id!==currentUser.id&&u.role!=='owner'?[button(tr('Change role','تغيير الدور'),async()=>{const role=prompt('owner / admin / support / finance / customer',u.role);if(!role)return;await api('/api/admin/users/'+u.id+'/role',{method:'PUT',body:JSON.stringify({role})});await open('roles',true)})]:[])]);box.append(node('p',tr('Only an owner can assign roles. Finance can manage platform payment methods through its authorized API. Support currently has account-only access.','المالك وحده يعيّن الأدوار. دور المالية يتيح إدارة وسائل المنصة عبر واجهته المصرح بها. الدعم يمتلك حاليًا صلاحيات الحساب الشخصي فقط.')))}
  async function logs(){const box=section(body,tr('Audit log','سجل الإجراءات'));let before;async function load(){const items=await api((platform?'/api/admin/logs':'/api/account/logs')+(before?'?before='+before:''));for(const r of items)row(box,r.action,new Date(r.created_at).toLocaleString());before=items.at(-1)?.id;more.hidden=items.length<100}const more=button(tr('Older records','سجلات أقدم'),load);body.append(more);await load()}
  async function locations(){const box=section(body,tr('Locations','المواقع'));let kind='countries',editing=null;const picker=select(box,tr('Type','النوع'),'type',[['countries',tr('Countries','الدول')],['regions',tr('Regions','المناطق')],['cities',tr('Cities','المدن')]]),list=node('div');box.append(list);const editor=section(body,tr('Location details','بيانات الموقع'));let parent;
    const f=form(editor,f=>{input(f,tr('Name','الاسم'),'name').required=true;input(f,tr('Country code','رمز الدولة'),'code');parent=select(f,tr('Parent location','الموقع الأب'),'parent_id',[]);select(f,tr('Enabled','مفعّل'),'enabled',[['true',tr('Yes','نعم')],['false',tr('No','لا')]])},tr('Save','حفظ'),async values=>{values.enabled=values.enabled==='true';values.parent_id=values.parent_id?Number(values.parent_id):null;values.code=values.code||null;await api('/api/admin/locations/'+kind+(editing?'/'+editing:''),{method:editing?'PUT':'POST',body:JSON.stringify(values)});await refresh()});
    async function refresh(){editing=null;f.reset();list.replaceChildren();parent.replaceChildren(new Option('—',''));if(kind!=='countries')for(const p of await api('/api/admin/locations/'+(kind==='regions'?'countries':'regions')))parent.add(new Option(p.name,p.id));for(const r of await api('/api/admin/locations/'+kind))row(list,r.name,r.enabled?tr('Enabled','مفعّل'):tr('Disabled','معطّل'),[button(tr('Edit','تعديل'),()=>{editing=r.id;for(const [k,v] of Object.entries({...r,parent_id:r.country_id||r.region_id||'',enabled:String(r.enabled)}))if(f.elements.namedItem(k))f.elements.namedItem(k).value=v}),button(tr('Disable','تعطيل'),async()=>{await api('/api/admin/locations/'+kind+'/'+r.id,{method:'DELETE'});await refresh()})])}
    picker.onchange=()=>{kind=picker.value;refresh().catch(e=>toast(e.message))};await refresh();
  }
  for(const [id,isAdmin] of [['accountPage',false],['adminPage',true]]){const host=$('#'+id+' .portal-content');const actions=node('div','','manage-actions');for(const [tab,en,ar] of (isAdmin?[['billing','Payment methods','وسائل الدفع'],['connections','Connections','الاتصالات'],['roles','Roles','الأدوار'],['locations','Locations','المواقع'],['logs','Audit logs','السجلات']]:[['security','Password & security','كلمة المرور والأمان'],['billing','Billing settings','إعدادات الفوترة'],['connections','GitHub','GitHub']]))actions.append(button(tr(en,ar),()=>open(tab,isAdmin)));host.prepend(actions)}
  $$('[data-go="billingPage"]').forEach(b=>b.onclick=()=>open('billing'));
  for(const [key,target] of [['ui60','connections'],['ui62','providers'],['ui63','security'],['ui64','security']]){const label=$('#accountPage .portal-nav [data-i18n="'+key+'"]');if(label){const b=label.closest('button');b.disabled=false;b.removeAttribute('title');b.onclick=()=>open(target)}}
  $$('#adminPage .portal-nav button').forEach(b=>{const name=b.textContent.trim();const target={'Payments':'billing','Countries & regions':'locations','Activity logs':'logs','Security logs':'logs'}[name];if(target){b.disabled=false;b.removeAttribute('title');b.onclick=()=>open(target,true)}});
  for(const p of $$('.page')){if(['landing','managementPage'].includes(p.id))continue;const h=$('header,.onboard-top,.project-bar',p);if(h)h.prepend(button(tr('← Back','← رجوع'),()=>page(p.id==='authPage'?'landing':'accountPage')))}
  const github=$('#chatGithub');if(github)github.onclick=()=>open('connections');
  const oldRefreshGit=refreshGit;refreshGit=async function(){await oldRefreshGit();const b=$('#manageProviders');if(b)b.onclick=()=>open('providers')};
  const welcome=$('#welcomePrompt');welcome.hidden=true;const connect=button(tr('Connect GitHub · choose repository & branch','اربط GitHub · اختر المستودع والفرع'),()=>open('connections'));connect.classList.add('landing-connect');const logo=document.createElementNS('http://www.w3.org/2000/svg','svg');const use=document.createElementNS('http://www.w3.org/2000/svg','use');use.setAttribute('href','#icon-github');logo.append(use);connect.prepend(logo);welcome.after(connect);
  const tools=node('div','','manage-actions workspace-links');tools.append(button(tr('Switch workspace','تبديل مساحة العمل'),()=>page('accountPage')),button(tr('Another repository','مستودع آخر'),()=>page('onboarding')));$('#promptForm').before(tools);
  const recovery=node('section','','manage-card recovery-box');recovery.hidden=true;$('#authPage').append(recovery);let resetToken=new URLSearchParams(location.hash.slice(1)).get('reset-password');if(resetToken)history.replaceState(null,'',location.pathname+location.search);
  function closeRecovery(){recovery.hidden=true;$('#authPage .auth-shell').hidden=false;window.scrollTo(0,0)}
  function recover(reset=false){showPage('authPage');$('#authPage .auth-shell').hidden=true;recovery.hidden=false;recovery.replaceChildren(node('h2',tr(reset?'Reset password':'Recover password',reset?'إعادة تعيين كلمة المرور':'استعادة كلمة المرور')));form(recovery,f=>{const i=input(f,tr(reset?'New password: 8+, number and symbol':'Account email',reset?'كلمة جديدة: 8 أحرف ورقم ورمز':'بريد الحساب'),reset?'password':'email',reset?'password':'email');i.required=true;if(reset)i.minLength=8},tr(reset?'Reset':'Send recovery link',reset?'إعادة تعيين':'إرسال رابط الاستعادة'),async values=>{const data=await api(reset?'/api/auth/reset-password':'/api/auth/forgot-password',{method:'POST',body:JSON.stringify(reset?{token:resetToken,password:values.password}:values)});toast(data.message);if(reset){resetToken=null;closeRecovery();signOut()}});recovery.append(button(tr('Back to login','رجوع للدخول'),closeRecovery));window.scrollTo(0,0)}
  const forgot=$('#authPage .auth-form .text-link');if(forgot){forgot.disabled=false;forgot.textContent=tr('Forgot password?','نسيت كلمة المرور؟');forgot.onclick=()=>recover()}
  if(resetToken)recover(true);
})();
